using System.Reflection;
using KingdomEnhancedMod;
using UnityEngine;

internal sealed class Fixture
{
 internal Cat Cat;internal Farmhouse Farm;internal World World;internal Kingdom Kingdom;
 internal Cat._FarmCatRoutine_d__74 Root=>Cat.fsm._states[3].CoroutineStack.Peek();
 internal Fixture()
 {
  foreach(var type in new[]{typeof(FarmCatMovement),typeof(PatchWorld_FarmCats)})
   foreach(var field in type.GetFields(BindingFlags.Static|BindingFlags.NonPublic))
   {
    var value=field.GetValue(null);var clear=value?.GetType().GetMethod("Clear",Type.EmptyTypes);
    if(clear!=null)clear.Invoke(value,null);else if(!field.IsInitOnly&&!field.IsLiteral)field.SetValue(null,field.FieldType.IsValueType?Activator.CreateInstance(field.FieldType):null);
   }
  Time.time=Time.fixedTime=100;Time.timeScale=1;ModConfig.Enabled.Value=true;NetworkBigBoss.IsOnline=false;NetworkBigBoss.HasWorldAuth=true;BiomeHolder.Inst=new();
  IslandSaveData.isSavingGame=false;IslandSaveData.CurrentlySavingIsland=null;Mover.Trace.Clear();Scene.Cats.Clear();Scene.Farms.Clear();Scene.Routines.Clear();Scene.Scans=Pool.Spawned=0;
  KingdomEnhancedPlugin.Instance.LogSource.Lines.Clear();KingdomEnhancedPlugin.Instance.LogSource.Throw=false;UnityEngine.Random.Fraction=.5f;
  World=new GameObject().AddComponent<World>();World.gameLayer=new GameObject().transform;World.gameLayer.parent=World.transform;
  Kingdom=new GameObject().AddComponent<Kingdom>();Kingdom.transform.parent=World.gameLayer;
  Managers.Inst=new(){world=World,kingdom=Kingdom};
  Farm=new GameObject().AddComponent<Farmhouse>();Farm.transform.parent=World.gameLayer;Scene.Farms.Add(Farm);
  Cat=MakeCat(Farm,0,World.gameLayer);Scene.Cats.Add(Cat);Cat.mover.SetGoal(2,.6f);
  Managers.Inst.holder.catPrefab=new GameObject().AddComponent<Cat>();Managers.Inst.holder.catPrefab.gameObject.scene.Valid=false;
 }
 internal static Cat MakeCat(Farmhouse farm,float x,Transform layer)
 {
  var go=new GameObject();go.transform.parent=layer;go.transform.position=new(x);
  var cat=go.AddComponent<Cat>();cat.domesticated=true;cat.farmHouse=farm;
  cat.mover=go.AddComponent<Mover>();cat.mover.rigidbody=go.AddComponent<Rigidbody2D>();go.AddComponent<Droppable>();
  cat.fsm=new(){_owner=cat};var state=new StateMachine.State();state.CoroutineStack.Push(new(){__4__this=cat});cat.fsm._states[3]=state;
  Cat_OnEnable_FarmMovement_Patch.Postfix(cat,true);return cat;
 }
 internal void Tick(float delta=.25f,bool originalRan=true,bool fixedAdvance=true)
 {
  Time.time+=delta;if(fixedAdvance)Time.fixedTime+=delta;
  if(originalRan)Cat.Update();Cat_Update_FarmMovement_Patch.Postfix(Cat,originalRan);
 }
 internal void Stall(float vx=0,int frames=18){for(int i=0;i<frames;i++){Cat.mover.rigidbody.velocity=new(vx);Tick();}}
 internal void Plot(float min,float max)
 {var plot=new GameObject().AddComponent<Farmland>();plot.transform.parent=World.gameLayer;plot.farmhouse=Farm;plot.gameObject.AddComponent<GAPS>().Region=new(min,max);Farm.farmlands.Add(plot);}
 internal Droppable Coin(float x)
 {var go=new GameObject();go.transform.parent=World.gameLayer;go.transform.position=new(x);var coin=go.AddComponent<Droppable>();coin.Subscribed=true;Cat.playCoin=coin;Cat.mover.ObjectGoal(go,2);Root.__1__state=4;return coin;}
 internal void Stock()=>typeof(PatchWorld_FarmCats).GetMethod("StockFarmCats",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{World});
}
internal static class Program
{
 static int passed,failed;static void Check(bool b,string why){if(!b)throw new Exception(why);}static void Eq<T>(T x,T y,string why){if(!EqualityComparer<T>.Default.Equals(x,y))throw new Exception($"{why}: expected {x}, got {y}");}
 static void Test(string name,Action<Fixture> body){try{body(new());passed++;Console.WriteLine("PASS "+name);}catch(Exception e){failed++;Console.WriteLine("FAIL "+name+": "+e.GetBaseException().Message);}}
 static void NoRestart(Fixture f){Eq(0,f.Cat.PlayCalls,"no cleanup");Eq(0,f.Cat.ResetCalls,"no reset");Check(!f.Cat.fsm._executeQueuedState,"no queued change");}
 static void Main()
 {
  Test("Position outside farm is projected with original goal speed",f=>{f.Cat.mover.SetGoal(10,1.7f);f.Tick();Eq(4f,f.Cat.mover._goalPosition,"home boundary");Eq(1.7f,f.Cat.mover._goalSpeed,"original speed");NoRestart(f);});
  Test("Separate farmland intervals preserve the gap",f=>{f.Plot(10,12);f.Cat.mover.SetGoal(8,.6f);f.Tick();Eq(10f,f.Cat.mover._goalPosition,"gap projects to real interval");});
  Test("A legal remote own farmland is not clipped to home eight",f=>{f.Plot(10,12);f.Cat.mover.SetGoal(11,.6f);int calls=f.Cat.mover.SetCalls;f.Tick();Eq(calls,f.Cat.mover.SetCalls,"far farm point kept");NoRestart(f);});
  Test("GAPS coordinates already world space",f=>{f.Farm.transform.position=new(100);f.Kingdom.Right=150;f.Plot(110,112);f.Cat.transform.position=new(100);f.Cat.mover.SetGoal(111,.6f);f.Tick();Eq(111f,f.Cat.mover._goalPosition,"no second x translation");});
  Test("Intact boundary and epsilon apply to target",f=>{f.Kingdom.Right=2;f.Cat.mover.SetGoal(4,.8f);f.Tick();Eq(1.9375f,f.Cat.mover._goalPosition,"inside intact edge");});
  Test("Readable same-root collider adds its extent",f=>{f.Cat.gameObject.AddComponent<Collider2D>();f.Kingdom.Right=2;f.Cat.mover.SetGoal(4,.8f);f.Tick();Eq(1.6875f,f.Cat.mover._goalPosition,"body extent inside edge");});
  Test("No collider remains legal center point policy",f=>{Check(f.Cat.GetComponent<Collider2D>()==null,"no collider fixture");f.Cat.mover.SetGoal(10,.6f);f.Tick();Eq(4f,f.Cat.mover._goalPosition,"point policy");});
  foreach(string invalid in new[]{"throw","nan"})Test("Unknown collider "+invalid+" does not write",f=>{var c=f.Cat.gameObject.AddComponent<Collider2D>();if(invalid=="throw")c.Throw=true;else c.Value=new(){extents=new(float.NaN)};f.Cat.mover.SetGoal(10,.6f);int calls=f.Cat.mover.SetCalls;f.Stall();Eq(calls,f.Cat.mover.SetCalls,"no target mutation");NoRestart(f);});
  foreach(string invalid in new[]{"missing","owner","inactive","nan","scale","throw"})Test("Unknown farmland "+invalid+" is not treated as empty/accessible",f=>{f.Plot(10,12);var p=f.Farm.farmlands[0];if(invalid=="missing")p.gameObject=new();if(invalid=="owner")p.farmhouse=null;if(invalid=="inactive")p.gameObject.activeInHierarchy=false;if(invalid=="nan")p.GetComponent<GAPS>().Region=new(float.NaN,12);if(invalid=="scale")p.transform.localScale=new(2,1,1);if(invalid=="throw")p.GetComponent<GAPS>().Throw=true;f.Cat.mover.SetGoal(10,.6f);int calls=f.Cat.mover.SetCalls;f.Stall();Eq(calls,f.Cat.mover.SetCalls,"zero target writes");NoRestart(f);});
  Test("World boundary unknown or empty gives zero writes",f=>{f.Kingdom.Left=40;f.Kingdom.Right=50;f.Stall();NoRestart(f);});
  Test("A moved Object goal is continuously checked",f=>{var coin=f.Coin(2);f.Tick();NoRestart(f);coin.transform.position=new(8);f.Tick();Eq(1,f.Cat.PlayCalls,"dynamic target canceled");Check(f.Cat.fsm._executeQueuedState,"restart pending");Eq(Mover.GoalMode.Off,f.Cat.mover.goalMode,"stop after queue");Eq(0,f.Cat.mover.SetCalls-1,"no Object-to-Position conversion");});
  Test("Cleanup queue Stop then native same-state reset cannot trigger wrong Catch",f=>{var coin=f.Coin(8);f.Cat.Sleeping=f.Cat.playingWithCoin=true;Mover.Trace.Clear();f.Tick();Eq("ResetCoin,EndPlay,Queue,Stop",string.Join(',',Mover.Trace),"ordered cancellation");Check(!coin.Subscribed&&!f.Cat.playingWithCoin,"native cleanup readback");Eq(0,f.Cat.Catches,"old wait not stepped after Stop");f.Tick();Eq(0,f.Cat.Catches,"new native Update resets before Step");Check(!f.Cat.Sleeping&&!f.Cat.fsm._executeQueuedState,"native callback completion");});
  Test("Blocked nonzero commanded velocity still restarts after four seconds",f=>{f.Stall(2);Eq(1,f.Cat.PlayCalls,"one recovery despite nonzero command");Check(f.Cat.transform.position.x==0,"blocked displacement");Eq(0,f.Cat.Catches,"no false catch");});
  Test("Native activity cooldown avoids immediate selection of the rejected coin",f=>{var coin=f.Coin(8);int reselected=0;f.Cat.NewActivity=()=>{if(Time.time>f.Cat.nextPlayWithCoinTime){reselected++;f.Cat.playCoin=coin;f.Cat.mover.ObjectGoal(coin.gameObject,2);f.Root.__1__state=4;}else{f.Cat.mover.SetGoal(1,.6f);f.Root.__1__state=8;}};f.Tick();Check(f.Cat.PlayStamp>=Time.time+5&&f.Cat.MouseStamp>=Time.time+5,"both native cooldown stamps");f.Tick();Eq(0,reselected,"native timer branch rejected immediate coin");Eq(1,f.Cat.PlayCalls,"one recovery only");Eq(8,f.Root.__1__state,"native rest movement retained");});
  Test("Larger native cooldowns are preserved without writes",f=>{f.Coin(8);f.Cat.PlayStamp=1000;f.Cat.MouseStamp=2000;f.Tick();Eq(1000f,f.Cat.PlayStamp,"play stamp preserved");Eq(2000f,f.Cat.MouseStamp,"mouse stamp preserved");Eq(0,f.Cat.PlayWrites,"no unnecessary write");Eq(0,f.Cat.MouseWrites,"no unnecessary write");});
  foreach(string failure in new[]{"playGet","mouseGet","playSet","mouseSet","playCommit","mouseCommit","playNaN","mouseNaN"})Test("Native cooldown "+failure+" failure keeps fault without queue/Stop/retry",f=>{f.Coin(8);switch(failure){case "playGet":f.Cat.ThrowPlayGet=true;break;case "mouseGet":f.Cat.ThrowMouseGet=true;break;case "playSet":f.Cat.ThrowPlaySet=true;break;case "mouseSet":f.Cat.ThrowMouseSet=true;break;case "playCommit":f.Cat.CommitPlayThrow=true;break;case "mouseCommit":f.Cat.CommitMouseThrow=true;break;case "playNaN":f.Cat.PlayStamp=float.NaN;break;case "mouseNaN":f.Cat.MouseStamp=float.NaN;break;}f.Tick();Check(!f.Cat.fsm._executeQueuedState,"no queue after timer fault");Eq(0,f.Cat.mover.Stops,"no stop after timer fault");int playWrites=f.Cat.PlayWrites,mouseWrites=f.Cat.MouseWrites;for(int i=0;i<24;i++)Cat_Update_FarmMovement_Patch.Postfix(f.Cat,true);Eq(playWrites,f.Cat.PlayWrites,"play write not retried");Eq(mouseWrites,f.Cat.MouseWrites,"mouse write not retried");Eq(1,f.Cat.ResetCalls,"cleanup not retried");if(failure=="mouseSet"||failure=="mouseCommit")Check(f.Cat.PlayStamp>=105,"first committed stamp retained");if(failure=="playCommit")Check(f.Cat.PlayStamp>=105,"ambiguous play commit not rolled back");if(failure=="mouseCommit")Check(f.Cat.MouseStamp>=105,"ambiguous mouse commit not rolled back");});
  Test("A larger mouse stamp changed after play commit is respected",f=>{f.Coin(8);f.Cat.OnPlayStamp=()=>f.Cat.MouseStamp=3000;f.Tick();Eq(3000f,f.Cat.MouseStamp,"fresh second commit boundary");Eq(0,f.Cat.MouseWrites,"external increase not overwritten");});
  Test("Foreign queued state during first timer commit stops the remaining sequence",f=>{f.Coin(8);f.Cat.OnPlayStamp=()=>{f.Cat.fsm._queuedState=4;f.Cat.fsm._executeQueuedState=true;};f.Tick();Eq(4,f.Cat.fsm._queuedState,"foreign queued state retained");Eq(0,f.Cat.MouseWrites,"no second write after scope request changed");Eq(0,f.Cat.mover.Stops,"no stop");});
  Test("Picked-up coin with still-live native wait is canceled",f=>{f.Coin(2).pickedUp=true;f.Tick();Eq(1,f.Cat.ResetCalls,"invalid coin canceled");Check(f.Cat.fsm._executeQueuedState,"normal restart queued");});
  Test("Normal walking resets no-progress",f=>{for(int i=0;i<24;i++){f.Cat.transform.position=new(i*.02f);f.Tick();}NoRestart(f);});
  Test("Equal back-and-forth net displacement is real progress",f=>{for(int i=0;i<24;i++){f.Cat.transform.position=new(i%2==0?.08f:0);f.Tick();}NoRestart(f);});
  Test("Small cumulative steps over threshold count as progress",f=>{for(int i=0;i<24;i++){f.Cat.transform.position=new(i*.004f);f.Tick();}NoRestart(f);});
  Test("Frozen fixedTime cannot prove three normal physics steps",f=>{for(int i=0;i<24;i++)f.Tick(fixedAdvance:false);NoRestart(f);});
  Test("Already reached target is not a stall",f=>{f.Cat.transform.position=new(2);f.Stall();NoRestart(f);});
  foreach(int pc in new[]{0,3,5,6,7,9,-1,10})Test("Nonmovement PC "+pc+" untouched",f=>{f.Root.__1__state=pc;for(int i=0;i<24;i++){Time.time+=.25f;Time.fixedTime+=.25f;Cat_Update_FarmMovement_Patch.Postfix(f.Cat,true);}NoRestart(f);});
  foreach(string gate in new[]{"off","foreign","online","client","pause","moverPause","loading","saveFlag","saveObject","wild","follow","grab","flee","embark","targetEmbark"})Test("Excluded "+gate+" has zero writes",f=>{switch(gate){case "off":ModConfig.Enabled.Value=false;break;case "foreign":BiomeHolder.Inst.BiomeIndex=0;break;case "online":NetworkBigBoss.IsOnline=true;break;case "client":NetworkBigBoss.HasWorldAuth=false;break;case "pause":Time.timeScale=0;break;case "moverPause":f.Cat.mover._pauseTimeout=10;break;case "loading":Managers.Inst.game.state=Game.State.Loading;break;case "saveFlag":IslandSaveData.isSavingGame=true;break;case "saveObject":IslandSaveData.CurrentlySavingIsland=new();break;case "wild":f.Cat.domesticated=false;break;case "follow":f.Cat.followingPlayer=f.Cat;break;case "grab":f.Cat.GetComponent<Droppable>().pickedUp=true;break;case "flee":f.Cat.fsm.Current=1;break;case "embark":f.Cat.gameObject.AddComponent<Embarkee>().IsEmbarked=true;break;case "targetEmbark":f.Cat.gameObject.AddComponent<Embarkee>().EmbarkableTarget=new();break;}f.Cat.mover.SetGoal(10,.6f);int calls=f.Cat.mover.SetCalls;f.Stall();Eq(calls,f.Cat.mover.SetCalls,"no goal writes");NoRestart(f);});
  foreach(string gate in new[]{"owner","sourceNull","sourceName","sourceType","iteratorOwner","stack","callbacks","body","farmLayer"})Test("Unproven native ownership "+gate+" stops adapter",f=>{switch(gate){case "owner":f.Cat.fsm._owner=f.Farm;break;case "sourceNull":f.Cat.fsm._states[3]._sourcePC=null;break;case "sourceName":f.Cat.fsm._states[3]._sourcePC.Name="other";break;case "sourceType":f.Cat.fsm._states[3]._sourcePC.DeclaringType.FullName="Other";break;case "iteratorOwner":f.Root.__4__this=null;break;case "stack":f.Cat.fsm._states[3].CoroutineStack.Push(new(){__4__this=f.Cat});break;case "callbacks":f.Cat.fsm._shouldRunCallbacks=false;break;case "body":f.Cat.mover.rigidbody=new GameObject().AddComponent<Rigidbody2D>();break;case "farmLayer":f.Farm.transform.parent=null;break;}f.Cat.mover.SetGoal(10,.6f);int calls=f.Cat.mover.SetCalls;for(int i=0;i<24;i++){Time.time+=.25f;Time.fixedTime+=.25f;Cat_Update_FarmMovement_Patch.Postfix(f.Cat,true);}Eq(calls,f.Cat.mover.SetCalls,"zero native writes");NoRestart(f);});
  Test("Foreign queued transition is never overwritten",f=>{f.Cat.fsm._executeQueuedState=true;f.Cat.fsm._queuedState=4;Cat_Update_FarmMovement_Patch.Postfix(f.Cat,true);Eq(4,f.Cat.fsm._queuedState,"native request retained");NoCleanup(f);});
  Test("Skipped original update cannot drive cleanup or projection",f=>{f.Cat.mover.SetGoal(10,.6f);int calls=f.Cat.mover.SetCalls;for(int i=0;i<24;i++)f.Tick(originalRan:false);Eq(calls,f.Cat.mover.SetCalls,"original-ran guard");NoRestart(f);});
  Test("A skipped original breaks the accumulated stall window",f=>{for(int i=0;i<12;i++)f.Tick();for(int i=0;i<12;i++)f.Tick(originalRan:false);f.Tick();NoRestart(f);});
  Test("World switch cannot drive old-world cats",f=>{for(int i=0;i<12;i++)f.Tick();var world=new GameObject().AddComponent<World>();world.gameLayer=new GameObject().transform;Managers.Inst.world=world;f.Stall();NoRestart(f);});
  Test("Cached geometry owner is rechecked at a write boundary",f=>{f.Plot(10,12);f.Tick();f.Cat.mover.SetGoal(8,.6f);f.Farm.farmlands[0].farmhouse=null;int calls=f.Cat.mover.SetCalls;f.Tick(.1f);Eq(calls,f.Cat.mover.SetCalls,"cached foreign plot does not authorize target write");NoRestart(f);});
  Test("Geometry getter changing plot ownership is rejected",f=>{f.Plot(10,12);var p=f.Farm.farmlands[0];p.GetComponent<GAPS>().OnRead=()=>p.farmhouse=null;f.Cat.mover.SetGoal(8,.6f);int calls=f.Cat.mover.SetCalls;f.Tick();Eq(calls,f.Cat.mover.SetCalls,"post-getter ownership recheck");});
  Test("Timer setter-side scope change is terminally checked",f=>{f.Coin(8);f.Cat.OnPlayStamp=()=>Managers.Inst.game.state=Game.State.Loading;f.Tick();Check(!f.Cat.fsm._executeQueuedState,"changed scope prevents queue");Eq(0,f.Cat.MouseWrites,"changed scope prevents second stamp");Eq(0,f.Cat.mover.Stops,"changed scope prevents stop");});
  foreach(float scale in new[]{float.NaN,float.PositiveInfinity})Test("Nonfinite timeScale "+scale+" is excluded",f=>{Time.timeScale=scale;f.Cat.mover.SetGoal(10,.6f);int calls=f.Cat.mover.SetCalls;f.Tick();Eq(calls,f.Cat.mover.SetCalls,"unknown scale zero writes");NoRestart(f);});
  Test("Fresh geometry losing authority prevents cleanup",f=>{f.Plot(10,12);f.Coin(8);int reads=0;f.Farm.farmlands[0].GetComponent<GAPS>().OnRead=()=>{if(++reads==2)NetworkBigBoss.HasWorldAuth=false;};f.Tick();NoCleanup(f);Eq(0,f.Cat.mover.Stops,"no stop after auth loss");});
  Test("Reset changing life prevents EndPlay on the new generation",f=>{f.Coin(8);f.Cat.playingWithCoin=true;f.Cat.OnReset=()=>{Cat_OnDisable_FarmMovement_Patch.Prefix(f.Cat);Cat_OnEnable_FarmMovement_Patch.Postfix(f.Cat,true);};f.Tick();Eq(0,f.Cat.PlayCalls,"no write to new generation");Check(f.Cat.playingWithCoin,"new generation flag retained");Eq(0,f.Cat.PlayWrites,"no native cooldown on new life");});
  foreach(string change in new[]{"auth","goal","queue"})Test("Reset callback changes "+change+" before EndPlay",f=>{f.Coin(8);f.Cat.OnReset=()=>{if(change=="auth")NetworkBigBoss.HasWorldAuth=false;if(change=="goal")f.Cat.mover.SetGoal(3,.9f);if(change=="queue"){f.Cat.fsm._executeQueuedState=true;f.Cat.fsm._queuedState=4;}};f.Tick();Eq(0,f.Cat.PlayCalls,"no EndPlay after ownership changed");Eq(0,f.Cat.mover.Stops,"no stop");if(change=="queue")Eq(4,f.Cat.fsm._queuedState,"queued native request retained");});
  foreach(float revoked in new[]{0f,float.NaN})Test("Second stamp setter revokes first to "+revoked+" without queue",f=>{f.Coin(8);f.Cat.OnMouseStamp=()=>f.Cat.PlayStamp=revoked;f.Tick();Check(!f.Cat.fsm._executeQueuedState,"joint acknowledgement required");Eq(0,f.Cat.mover.Stops,"no stop on revoked stamp");int writes=f.Cat.PlayWrites+f.Cat.MouseWrites;for(int i=0;i<24;i++)Cat_Update_FarmMovement_Patch.Postfix(f.Cat,true);Eq(writes,f.Cat.PlayWrites+f.Cat.MouseWrites,"no repair rewrite");});
  Test("Mouse getter raises play stamp before its commit",f=>{f.Coin(8);int reads=0;f.Cat.OnMouseRead=()=>{if(++reads==1)f.Cat.PlayStamp=1000;};f.Tick();Eq(1000f,f.Cat.PlayStamp,"larger value preserved");Eq(0,f.Cat.PlayWrites,"not overwritten by stale plan");});
  foreach(string change in new[]{"scope","life","goal"})Test("Timer getter changes "+change+" before any stamp commit",f=>{f.Coin(8);f.Cat.OnMouseRead=()=>{if(change=="scope")Managers.Inst.game.state=Game.State.Loading;if(change=="life"){Cat_OnDisable_FarmMovement_Patch.Prefix(f.Cat);Cat_OnEnable_FarmMovement_Patch.Postfix(f.Cat,true);}if(change=="goal")f.Cat.mover.SetGoal(3,.8f);};f.Tick();Eq(0,f.Cat.PlayWrites,"no first timer write");Eq(0,f.Cat.MouseWrites,"no second timer write");Check(!f.Cat.fsm._executeQueuedState,"no queue on changed read context");Eq(0,f.Cat.mover.Stops,"no stop");});
  Test("Diagnostic failure does not turn a completed projection into a fault",f=>{KingdomEnhancedPlugin.Instance.LogSource.Throw=true;f.Cat.mover.SetGoal(10,.6f);f.Tick();f.Cat.mover.SetGoal(-10,.6f);f.Tick();Eq(-4f,f.Cat.mover._goalPosition,"second legitimate projection still succeeds");});
  foreach(string failure in new[]{"reset","play","queue","stop"})Test("Partial native "+failure+" failure is not retried",f=>{f.Coin(8);switch(failure){case "reset":f.Cat.ThrowReset=true;break;case "play":f.Cat.ThrowPlay=true;break;case "queue":f.Cat.fsm.ThrowQueue=true;break;case "stop":f.Cat.mover.ThrowStop=true;break;}f.Tick();int resets=f.Cat.ResetCalls,plays=f.Cat.PlayCalls;for(int i=0;i<24;i++)Cat_Update_FarmMovement_Patch.Postfix(f.Cat,true);Eq(resets,f.Cat.ResetCalls,"no repeated cleanup");Eq(plays,f.Cat.PlayCalls,"no repeated event");});
  Test("Cleanup readback failure does not queue or Stop",f=>{f.Coin(8);f.Cat.OnPlay=()=>NetworkBigBoss.HasWorldAuth=false;f.Tick();Check(!f.Cat.fsm._executeQueuedState,"no queue after auth lost");Eq(0,f.Cat.mover.Stops,"no Stop");});
  Test("A native queue appearing during cleanup is respected",f=>{f.Coin(8);f.Cat.OnPlay=()=>{f.Cat.fsm._executeQueuedState=true;f.Cat.fsm._queuedState=4;};f.Tick();Eq(4,f.Cat.fsm._queuedState,"grab request not overwritten");Eq(0,f.Cat.mover.Stops,"no stop without owned queued reset");});
  Test("Enable generation changed during cleanup cannot inherit old recovery",f=>{f.Coin(8);f.Cat.OnReset=()=>{Cat_OnDisable_FarmMovement_Patch.Prefix(f.Cat);Cat_OnEnable_FarmMovement_Patch.Postfix(f.Cat,true);};f.Tick();Check(!f.Cat.fsm._executeQueuedState,"old life cannot queue");Eq(0,f.Cat.mover.Stops,"old life cannot stop");});
  Test("Disable and re-enable discard old displacement window",f=>{for(int i=0;i<12;i++)f.Tick();Cat_OnDisable_FarmMovement_Patch.Prefix(f.Cat);Cat_OnEnable_FarmMovement_Patch.Postfix(f.Cat,true);for(int i=0;i<8;i++)f.Tick();NoRestart(f);});
  Test("Pause resets the prior window",f=>{for(int i=0;i<12;i++)f.Tick();Time.timeScale=0;f.Tick();Time.timeScale=1;for(int i=0;i<8;i++)f.Tick();NoRestart(f);});
  Test("Phase and goal changes reset the prior window",f=>{for(int i=0;i<12;i++)f.Tick();f.Root.__1__state=8;f.Cat.mover.SetGoal(3,.6f);for(int i=0;i<8;i++)f.Tick();NoRestart(f);});
  Test("Position write throws do not retry an uncertain mutation",f=>{f.Cat.mover.SetGoal(10,.6f);f.Cat.mover.ThrowSet=true;f.Tick();int calls=f.Cat.mover.SetCalls;f.Cat.mover.ThrowSet=false;for(int i=0;i<24;i++)Cat_Update_FarmMovement_Patch.Postfix(f.Cat,true);Eq(calls,f.Cat.mover.SetCalls,"write fault retained");});
  Test("Birth is projected inside home and intact overlap",f=>{f.Kingdom.Right=2;UnityEngine.Random.Fraction=.99f;f.Stock();Check(Scene.Cats.All(c=>c.transform.position.x<=1.9375f),"no new cat born outside edge");Eq(3,Pool.Spawned,"only deficit");});
  Test("Empty birth intersection defers without consuming normal stock guard",f=>{f.Kingdom.Left=10;f.Kingdom.Right=20;f.Stock();Eq(0,Pool.Spawned,"deferred birth");f.Kingdom.Left=-30;f.Kingdom.Right=30;f.Stock();Eq(3,Pool.Spawned,"later normal stock can fill deficit");});
  Test("Movement maintenance never scans the scene",f=>{f.Stall();Eq(0,Scene.Scans,"no new scanning driver");});
  Console.WriteLine($"RESULT {passed} passed, {failed} failed");Environment.ExitCode=failed==0?0:1;
 }
 static void NoCleanup(Fixture f){Eq(0,f.Cat.ResetCalls,"no cleanup");Eq(0,f.Cat.PlayCalls,"no event");}
}
