<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>disable</Nullable></PropertyGroup><ItemGroup><Compile Include="../../il2cpp/PatchRoles_DeadlandsPowers.cs" Link="Production/PatchRoles_DeadlandsPowers.cs" /><Compile Include="../../il2cpp/PatchRoles_MedievalNorsePowers.cs" Link="Production/PatchRoles_MedievalNorsePowers.cs" /></ItemGroup></Project>
