using System.Reflection;
using KingdomEnhancedMod;
using UnityEngine;
using Coatsink.Common;
internal static partial class Program
{
 static int passed,failed;static readonly List<Mover> Movers=new();
 static void Eq<T>(T expected,T actual,string why){if(!EqualityComparer<T>.Default.Equals(expected,actual))throw new Exception($"{why}: expected {expected}, got {actual}");}
 static void Near(float expected,float actual,string why){if(MathF.Abs(expected-actual)>.001f)throw new Exception($"{why}: expected {expected}, got {actual}");}
 static void Check(bool b,string why){if(!b)throw new Exception(why);}
 static bool Prefix(Mover m,GameObject goal,float speed,ref float offset,Mover.OffsetMode mode)
 {
  var method=typeof(PatchWorld_DefenseSpacing).GetMethod("NightFollowerAnchorPrefix",BindingFlags.Static|BindingFlags.Public|BindingFlags.NonPublic);
  var args=new object[]{m,goal,speed,offset,mode};bool result=(bool)method.Invoke(null,args);offset=(float)args[3];
  Check(ReferenceEquals(goal,args[1]),"prefix keeps original goal object");Near(speed,(float)args[2],"prefix keeps native speed");Eq(mode,(Mover.OffsetMode)args[4],"prefix keeps native offset mode");return result;
 }
 static void Test(string name,Action action)
 {
  SquadFollowGuard.Clear();Movers.Clear();Mover.Intercept=Prefix;ModConfig.Enabled.Value=true;NetworkBigBoss.HasWorldAuth=true;Time.time=100;Time.timeScale=1;Managers.Inst=new();UnityEngine.Object.Forbidden=0;KingdomEnhancedPlugin.Instance.LogSource.Throw=false;KingdomEnhancedPlugin.Instance.LogSource.Lines.Clear();
  try{action();Eq(0,UnityEngine.Object.Forbidden,"no extra scene scans");Check(Movers.All(m=>m.Stops==0&&m.Unpauses==0),"no Stop or UnPause of native tasks");passed++;Console.WriteLine("PASS "+name);}catch(Exception e){failed++;Console.WriteLine("FAIL "+name+": "+e.GetBaseException().Message);}
 }
 static (Knight k,Archer a,Mover m) Pair(Side side=Side.Right,float? x=null)
 {
  var kg=new GameObject();var k=kg.AddComponent<Knight>();k.side=side;k.transform.parent=Managers.Inst?.world?.gameLayer;k.transform.position=new(x??(side==Side.Left?-98:98));k.transform.localScale=new((float)side,1,1);k._character=kg.AddComponent<Character>();k._damageable=kg.AddComponent<Damageable>();k._mover=kg.AddComponent<Mover>();
  var ag=new GameObject();var a=ag.AddComponent<Archer>();a._knight=k;a.transform.parent=Managers.Inst?.world?.gameLayer;a._character=ag.AddComponent<Character>();a._damageable=ag.AddComponent<Damageable>();a._mover=ag.AddComponent<Mover>();Movers.Add(a._mover);return(k,a,a._mover);
 }
 static Wait Follow(Knight k,Mover m,float offset=-1,float speed=5,Mover.OffsetMode mode=Mover.OffsetMode.Formation)=>m.SetGoal(k.gameObject,speed,offset,mode);
 static void Guarded(Knight k,Mover m){var wait=Follow(k,m);Check(wait!=null&&ReferenceEquals(wait,m.LastWait),"native Wait preserved");Eq(Mover.GoalMode.Object,m.goalMode,"Object mode preserved");Check(ReferenceEquals(k.gameObject,m._goalObject),"native owner target preserved");Check(MathF.Abs(m._goalOffset+1)>.1f,"test actually acquired guard receipt");}
 static Haglet Behaviour(Archer a)=>(Haglet)a.behaviour;
 static void Main()
 {
  Test("Original prefix causally reproduces fixed-wall Position and missing native Wait",()=>{var(k,a,m)=Pair();Mover.Intercept=(Mover mm,GameObject g,float speed,ref float offset,Mover.OffsetMode mode)=>LegacyDefenseSpacing.NightFollowerAnchorPrefix(mm,g,speed,offset,mode);var wait=Follow(k,m);Check(wait==null,"old prefix skipped native Object Wait");Eq(Mover.GoalMode.Position,m.goalMode,"legacy clamped to fixed position");float fixedX=m.DynamicDestination;k.transform.position=new(120);Near(fixedX,m.DynamicDestination,"legacy follower stays at old wall target");});
  Test("Night guard preserves native Object target and Wait then follows advancing knight",()=>{var(k,a,m)=Pair();Guarded(k,m);Near(95.8f,m.DynamicDestination,"guard anchor stays inside right wall");k.isCharging=true;k._fsm.Current=Knight.State.Charge;k.transform.position=new(120);SquadFollowGuard.Reconcile();Near(-1,m._goalOffset,"original follow offset restored");Near(119,m.DynamicDestination,"target travels with expedition leader");Eq(0,m.PositionCalls,"never converted follow to Position");});
  foreach(var side in new[]{Side.Left,Side.Right})foreach(float facing in new[]{-1f,1f})Test("Wall anchor side="+side+" facing="+facing,()=>{var(k,a,m)=Pair(side);k.transform.localScale=new(facing,1,1);Guarded(k,m);Near((float)side*95.8f,m.DynamicDestination,"offset accounts for actual facing, not side approximation");Near(5,m._goalSpeed,"native speed unchanged");});
  Test("AdjustAnchor itself never invokes native SetGoal",()=>{var(k,a,m)=Pair();float offset=-1;SquadFollowGuard.AdjustAnchor(m,k.gameObject,5,ref offset,Mover.OffsetMode.Formation);Eq(0,m.ObjectCalls,"no nested native Object call in prefix helper");Eq(0,m.PositionCalls,"no float call");Near(-2.2f,offset,"only ref offset adjusted");});
  Test("Deep valid follower position is not needlessly clamped",()=>{var(k,a,m)=Pair();Follow(k,m,-8);Near(-8,m._goalOffset,"existing deeper anchor preserved");});
  Test("Deadlands wall pullback retains its existing deeper value",()=>{var(k,a,m)=Pair();k.Style=1;Follow(k,m);Near(93.5f,m.DynamicDestination,"existing 6.5-depth wall behavior");});
  Test("Leader beyond defensive wall band is never clamped",()=>{var(k,a,m)=Pair(x:120);Follow(k,m);Near(-1,m._goalOffset,"outbound offset untouched");});
  foreach(var entry in new (string,Action<Knight>)[]{("charging",k=>k.isCharging=true),("pending charge",k=>k._shouldCharge=true),("formation",k=>k.Formation=new()),("embarked",k=>k._embarkee.IsEmbarked=true),("boat target",k=>k._embarkee.EmbarkableTarget=new object()),("manual control",k=>k.ControlRequested=true),("already controlled",k=>k._beingControlled=true),("pillar task",k=>k.helPuzzlePillar=new()),("other FSM",k=>k._fsm.Current=Knight.State.Assemble)})Test("Expedition leader gate "+entry.Item1,()=>{var(k,a,m)=Pair();entry.Item2(k);Check(!SquadFollowGuard.IsWallFollower(a,Managers.Inst.kingdom),"mission follower excluded from parked sweep");Follow(k,m);Near(-1,m._goalOffset,"native expedition follow unchanged");});
  foreach(var entry in new (string,Action<Archer>)[]{("tower",a=>a._guardSlot=new()),("formation",a=>a.Formation=new()),("boat target",a=>a._embarkee.EmbarkableTarget=new object()),("manual control",a=>a.ControlRequested=true),("inert",a=>a._character.inert=true),("grabbed",a=>a._character.grabbed=true),("dead",a=>a._damageable.isDead=true),("not follow2",a=>Behaviour(a).latestGoto=8)})Test("Follower higher task gate "+entry.Item1,()=>{var(k,a,m)=Pair();entry.Item2(a);Follow(k,m);Near(-1,m._goalOffset,"higher Archer task untouched");});
  Test("Dawn releases only owned offset while retaining dynamic native follow",()=>{var(k,a,m)=Pair();Guarded(k,m);Managers.Inst.kingdom.isDaytime=true;SquadFollowGuard.Reconcile();Near(-1,m._goalOffset,"dawn restores baseline");Eq(Mover.GoalMode.Object,m.goalMode,"still Object");Eq(1,m.ObjectCalls,"restoration writes offset only");SquadFollowGuard.Reconcile();Eq(1,m.ObjectCalls,"dormant receipt never replays SetGoal");});
  Test("Mod disable releases owned offset without reclamping",()=>{var(k,a,m)=Pair();Guarded(k,m);ModConfig.Enabled.Value=false;SquadFollowGuard.Reconcile();Near(-1,m._goalOffset,"disabled restore");});
  Test("Paused mover retains receipt and pause until motion resumes",()=>{var(k,a,m)=Pair();Guarded(k,m);m._pauseTimeout=.5f;k.isCharging=true;SquadFollowGuard.Reconcile();Eq(1,m.ObjectCalls,"no overwrite during external pause");Near(.5f,m._pauseTimeout,"pause preserved");m._pauseTimeout=0;SquadFollowGuard.Reconcile();Near(-1,m._goalOffset,"receipt restored after pause");});
  Test("Global pause retains owned receipt until scaled play resumes",()=>{var(k,a,m)=Pair();Guarded(k,m);k.isCharging=true;Time.timeScale=0;SquadFollowGuard.Reconcile();Eq(1,m.ObjectCalls,"no restore write while game is paused");Time.timeScale=1;SquadFollowGuard.Reconcile();Near(-1,m._goalOffset,"resume restores retained offset");});
  Test("Lost authority retires receipt without any goal write",()=>{var(k,a,m)=Pair();Guarded(k,m);k.isCharging=true;NetworkBigBoss.HasWorldAuth=false;SquadFollowGuard.Reconcile();Eq(1,m.ObjectCalls,"client never writes restore");NetworkBigBoss.HasWorldAuth=true;SquadFollowGuard.Reconcile();Eq(1,m.ObjectCalls,"retired receipt does not return later");});
  foreach(var change in new (string,Action<Knight,Archer,Mover>)[]{("external Position",(k,a,m)=>m.SetGoal(300,9)),("external speed",(k,a,m)=>m._goalSpeed=9),("external offset",(k,a,m)=>m._goalOffset=-9),("new owner",(k,a,m)=>a._knight=Pair().k),("new mover",(k,a,m)=>a._mover=new GameObject().AddComponent<Mover>()),("Archer mission",(k,a,m)=>Behaviour(a).latestGoto=10)})Test("Reconcile preserves "+change.Item1,()=>{var(k,a,m)=Pair();Guarded(k,m);change.Item2(k,a,m);int writes=m.ObjectCalls;float offset=m._goalOffset;k.isCharging=true;SquadFollowGuard.Reconcile();Eq(writes,m.ObjectCalls,"external ownership not overwritten");Near(change.Item1=="Archer mission"?-1:offset,m._goalOffset,"owned mission offset restored; external tuple left alone");});
  Test("Clear only drops receipts without touching native goals",()=>{var(k,a,m)=Pair();Guarded(k,m);float offset=m._goalOffset;SquadFollowGuard.Clear();k.isCharging=true;SquadFollowGuard.Reconcile();Near(offset,m._goalOffset,"clear is bookkeeping only");Eq(1,m.ObjectCalls,"no clear-time goal write");});
  Test("Same owned native reassertion does not lose original baseline",()=>{var(k,a,m)=Pair();Guarded(k,m);Follow(k,m,m._goalOffset);k.isCharging=true;SquadFollowGuard.Reconcile();Near(-1,m._goalOffset,"original offset survives exact owned reassertion");});
  Test("Exact owned reassertion after leader starts charging retains releasable baseline",()=>{var(k,a,m)=Pair();Guarded(k,m);k.isCharging=true;Follow(k,m,m._goalOffset);SquadFollowGuard.Reconcile();Near(-1,m._goalOffset,"charge-before-reassert must release old wall offset");});
  Test("Exact owned reassertion after config disable retains releasable baseline",()=>{var(k,a,m)=Pair();Guarded(k,m);ModConfig.Enabled.Value=false;Follow(k,m,m._goalOffset);SquadFollowGuard.Reconcile();Near(-1,m._goalOffset,"disable-before-reassert must release old wall offset");});
  Test("Paused exact reassertion retains original baseline until pause ends",()=>{var(k,a,m)=Pair();Guarded(k,m);float written=m._goalOffset;k.isCharging=true;m._pauseTimeout=.5f;Follow(k,m,written);SquadFollowGuard.Reconcile();Near(written,m._goalOffset,"pause retains adjusted tuple");Near(.5f,m._pauseTimeout,"native pause not cleared by reassert");m._pauseTimeout=0;SquadFollowGuard.Reconcile();Near(-1,m._goalOffset,"resume restores original baseline after reassert");});
  Test("Destroyed mover receipt releases ledger and snapshot references",()=>{var(k,a,m)=Pair();Guarded(k,m);m.Destroyed=true;SquadFollowGuard.Reconcile();foreach(var field in typeof(SquadFollowGuard).GetFields(BindingFlags.Static|BindingFlags.NonPublic))if(field.GetValue(null) is System.Collections.IDictionary dict)Eq(0,dict.Count,"dead mover key retired");else if(field.GetValue(null) is System.Collections.IList list)Eq(0,list.Count,"temporary snapshot released");});
  Test("New native baseline is restored instead of stale first offset",()=>{var(k,a,m)=Pair();Guarded(k,m);Follow(k,m,-.25f);k.isCharging=true;SquadFollowGuard.Reconcile();Near(-.25f,m._goalOffset,"latest native argument becomes baseline");});
  Test("Offset restore does not invoke native goal callbacks and later external task survives",()=>{var(k,a,m)=Pair();Guarded(k,m);k.isCharging=true;bool callback=false;m.OnObjectGoal=()=>callback=true;SquadFollowGuard.Reconcile();Check(!callback,"field restoration never invokes native SetGoal callback");Near(-1,m._goalOffset,"baseline restored");m.SetGoal(300,9);SquadFollowGuard.Reconcile();Near(300,m.DynamicDestination,"external native target retained");});
  Test("Offset restore bypasses throwing native SetGoal and permits subsequent owners",()=>{var(k,a,m)=Pair();Guarded(k,m);k.isCharging=true;m.ThrowOnObjectGoal=true;SquadFollowGuard.Reconcile();Near(-1,m._goalOffset,"field restore cannot trigger SetGoal exception");var(next,b,n)=Pair();Follow(next,n);Check(MathF.Abs(n._goalOffset+1)>.1f,"restoring guard cleared in finally");});
  Test("Knightless wall mirror requires native wall8 and excludes other tasks",()=>{var(k,a,m)=Pair();a._knight=null;Behaviour(a).latestGoto=8;Check(SquadFollowGuard.IsOrdinaryWallArcher(a),"ordinary ground wall archer allowed");Behaviour(a).latestGoto=10;Check(!SquadFollowGuard.IsOrdinaryWallArcher(a),"chase/flee mission not wall");Behaviour(a).latestGoto=8;a.ControlRequested=true;Check(!SquadFollowGuard.IsOrdinaryWallArcher(a),"manual archer not wall");});
  Test("Day knight spread requires actual Assemble state without expedition intent",()=>{var(k,a,m)=Pair();k._fsm.Current=Knight.State.Assemble;Check(SquadFollowGuard.IsDayAssemblingKnight(k),"normal Assemble allowed");k.isCharging=true;Check(!SquadFollowGuard.IsDayAssemblingKnight(k),"expedition Assemble transition excluded");k.isCharging=false;k._fsm.Current=Knight.State.Stand;Check(!SquadFollowGuard.IsDayAssemblingKnight(k),"other state not daytime Assemble");});
  RunFrameTests();
  RunStationTests();
  RunObserveTests();
  RunWorldTests();
  Console.WriteLine($"RESULT {passed} passed, {failed} failed");Environment.ExitCode=failed==0?0:1;
 }
}
