using System.Reflection;
using KingdomEnhancedMod;
using UnityEngine;
internal static class Program
{
 static int passed,failed;
 static readonly Type Production=typeof(PatchWorld_FarmCats);
 static readonly Dictionary<FieldInfo,object> Defaults=Production.GetFields(BindingFlags.Static|BindingFlags.Public|BindingFlags.NonPublic).Where(f=>!f.IsLiteral&&!f.IsInitOnly).ToDictionary(f=>f,f=>f.GetValue(null));
 static void Check(bool b,string why){if(!b)throw new Exception(why);}static void Eq<T>(T expected,T actual,string why){if(!EqualityComparer<T>.Default.Equals(expected,actual))throw new Exception($"{why}: expected {expected}, got {actual}");}
 static void Test(string name,Action body)
 {
  foreach(var field in Defaults)field.Key.SetValue(null,field.Value);Scene.Cats.Clear();Scene.Farms.Clear();Scene.Routines.Clear();Pool.Retired.Clear();Pool.Spawned=0;Pool.Deferred=Pool.ThrowRetire=false;Pool.RetireOverride=null;
  ModConfig.Enabled.Value=true;NetworkBigBoss.HasWorldAuth=true;NetworkBigBoss.IsOnline=false;Managers.Inst=new();BiomeHolder.Inst=new();
  Managers.Inst.holder.catPrefab=new GameObject().AddComponent<Cat>();UnityEngine.Object.SceneScans=UnityEngine.Object.Forbidden=0;KingdomEnhancedPlugin.Instance.LogSource.Throw=false;KingdomEnhancedPlugin.Instance.LogSource.Lines.Clear();
  try{body();Eq(0,UnityEngine.Object.Forbidden,"no new scene query types");passed++;Console.WriteLine("PASS "+name);}catch(Exception e){failed++;Console.WriteLine("FAIL "+name+": "+e.GetBaseException().Message);}
 }
 static Farmhouse Farm(bool listed=true){var farm=new GameObject().AddComponent<Farmhouse>();if(listed)Scene.Farms.Add(farm);return farm;}
 static Cat Cat(Farmhouse farm,bool mod=true,bool domestic=true)
 {var go=new GameObject{name=mod?"KEM_FarmCat_old_save":"NativeCat"};var cat=go.AddComponent<Cat>();cat.farmHouse=farm;cat.domesticated=domestic;go.AddComponent<Droppable>();Scene.Cats.Add(cat);return cat;}
 static Cat[] Cats(Farmhouse farm,int count,bool mod=true)=>Enumerable.Range(0,count).Select(_=>Cat(farm,mod)).ToArray();
 static int Alive(Farmhouse farm)=>Scene.Cats.Count(c=>c.gameObject.activeInHierarchy&&c.domesticated&&c.farmHouse==farm);
 static World World()=>new GameObject().AddComponent<World>();
 static void Stock(World world)=>Production.GetMethod("StockFarmCats",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,new object[]{world});
 static bool Retire(Cat cat,Farmhouse farm)=>Retire(cat,farm,out _);
 static bool Retire(Cat cat,Farmhouse farm,out bool uncertain){object[] args={cat,farm,false};bool result=(bool)Production.GetMethod("TryRetireFarmCat",BindingFlags.Static|BindingFlags.NonPublic).Invoke(null,args);uncertain=(bool)args[2];return result;}
 static void Main()
 {
  Test("Old six marked farm cats reduce to exactly four",()=>{var f=Farm();Cats(f,6);Stock(World());Eq(4,Alive(f),"four cats remain");Eq(2,Pool.Retired.Count,"only two excess cats retired");Eq(0,Pool.Spawned,"no replacement spawn");});
  Test("Two native plus four mod cats keep native and remove only two mod cats",()=>{var f=Farm();var native=Cats(f,2,false);Cats(f,4);Stock(World());Eq(4,Alive(f),"combined total four");Check(native.All(c=>c.gameObject.activeInHierarchy),"all native cats retained");Check(Pool.Retired.All(go=>go.name.StartsWith("KEM_FarmCat")),"only marked instances retired");});
  Test("More than four native cats are never removed",()=>{var f=Farm();Cats(f,6,false);Stock(World());Eq(6,Alive(f),"native population preserved");Eq(0,Pool.Retired.Count,"native cats not deleted");Eq(0,Pool.Spawned,"already over target");});
  Test("Native surplus remains even after removable mod cats are exhausted",()=>{var f=Farm();var native=Cats(f,6,false);Cats(f,2);Stock(World());Eq(6,Alive(f),"native six retained");Eq(2,Pool.Retired.Count,"only mod surplus removed");Check(native.All(c=>c.gameObject.activeInHierarchy),"native cats stay active");});
  Test("Already four cats are not retired or supplemented",()=>{var f=Farm();Cats(f,4);Stock(World());Eq(0,Pool.Retired.Count,"no retire at target");Eq(0,Pool.Spawned,"no spawn at target");});
  Test("Underfilled farmhouse is supplemented to four using original spawn path",()=>{var f=Farm();Cats(f,1);Stock(World());Eq(4,Alive(f),"fills to four");Eq(3,Pool.Spawned,"only deficit spawned");Check(Scene.Cats.All(c=>c.domesticated&&c.farmHouse==f),"spawn setup unchanged");});
  Test("Deferred native Destroy still retires only the two surplus cats",()=>{var f=Farm();Cats(f,6);Pool.Deferred=true;Stock(World());Eq(2,Pool.Retired.Count,"does not delete all six while destruction is pending");Eq(4,Alive(f),"active count immediately four");Check(Pool.Retired.All(go=>go.PendingDestroy&&!go.activeInHierarchy),"pending deletion is synchronously inactive");Eq(0,Pool.Spawned,"no false replacement spawn");});
  Test("Picked-up and player-following cats cannot be selected for retirement",()=>{var f=Farm();var cats=Cats(f,6);cats[5].GetComponent<Droppable>().pickedUp=true;cats[4].followingPlayer=new object();Stock(World());Check(cats[5].gameObject.activeInHierarchy&&cats[4].gameObject.activeInHierarchy,"protected cats survive");Eq(4,Alive(f),"remove two eligible alternatives only");});
  Test("All protected marked cats remain above target without forced retirement",()=>{var f=Farm();var cats=Cats(f,6);foreach(var c in cats)c.GetComponent<Droppable>().pickedUp=true;Stock(World());Eq(6,Alive(f),"protected population kept");Eq(0,Pool.Retired.Count,"no native retirement call");Eq(0,Pool.Spawned,"no supplemental cats");});
  Test("Different farm, unbound, wild and unmarked cats fail direct retirement recheck",()=>{var f=Farm();var other=Farm(false);var foreign=Cat(other);var unbound=Cat(null);var wild=Cat(f,domestic:false);var native=Cat(f,mod:false);Check(!Retire(foreign,f)&&!Retire(unbound,f)&&!Retire(wild,f)&&!Retire(native,f),"unrelated or unsafe cats rejected");Eq(0,Pool.Retired.Count,"no native retire calls");});
  Test("Stock cleanup never crosses farmhouse binding",()=>{var f=Farm();var other=Farm(false);Cats(f,6);var foreign=Cats(other,6);Stock(World());Eq(4,Alive(f),"target farm reduced");Check(foreign.All(c=>c.gameObject.activeInHierarchy),"unlisted other farm untouched");});
  Test("Failed retire calls stop this farmhouse without decrementing count or spawning replacements",()=>{var f=Farm();Cats(f,6);Pool.ThrowRetire=true;Stock(World());Eq(6,Alive(f),"failed retirees remain counted");Eq(1,Pool.Retired.Count,"stop after first uncertain retirement");Eq(0,Pool.Spawned,"failure never creates compensating extra cats");Check(KingdomEnhancedPlugin.Instance.LogSource.Lines.Any(l=>l.Contains("retired 0")),"summary counts only successful retirement");});
  Test("Online world performs no cat changes or scans and does not consume single-player guard",()=>{var f=Farm();Cats(f,6);var w=World();NetworkBigBoss.IsOnline=true;Stock(w);Eq(6,Alive(f),"online cats unchanged");Eq(0,UnityEngine.Object.SceneScans,"online skips scans");Eq(0,Pool.Retired.Count,"online no retire");NetworkBigBoss.IsOnline=false;Stock(w);Eq(4,Alive(f),"later eligible load still runs");});
  Test("Non-Greek biome and non-authoritative world remain untouched",()=>{var f=Farm();Cats(f,6);BiomeHolder.Inst.BiomeIndex=0;Stock(World());Eq(6,Alive(f),"non-Greek unchanged");BiomeHolder.Inst.BiomeIndex=5;NetworkBigBoss.HasWorldAuth=false;Stock(World());Eq(6,Alive(f),"client unchanged");Eq(0,UnityEngine.Object.SceneScans,"excluded worlds skip scans");});
  Test("Config-off actual level-load hook does not schedule stocking",()=>{ModConfig.Enabled.Value=false;var hook=typeof(World_FarmCats_Stock_Host_Patch).GetMethod("Postfix",BindingFlags.Static|BindingFlags.NonPublic);hook.Invoke(null,new object[]{World()});Eq(0,Scene.Routines.Count,"disabled hook does not schedule coroutine");});
  Test("Repeated same-world load is idempotent and does not scan again",()=>{var f=Farm();Cats(f,6);var w=World();Stock(w);int scans=UnityEngine.Object.SceneScans;Stock(w);Eq(4,Alive(f),"stable population");Eq(2,Pool.Retired.Count,"no further retire");Eq(scans,UnityEngine.Object.SceneScans,"no repeated same-world scan");});
  Test("Pool deactivation followed by exception counts actual completed retirement",()=>{var f=Farm();Cats(f,6);Pool.RetireOverride=go=>{go.SetActive(false);throw new InvalidOperationException("Pool callback failed after deactivation");};Stock(World());Eq(4,Alive(f),"exactly four remain despite callback errors");Eq(2,Pool.Retired.Count,"completed side effects counted, not all six retired");Eq(0,Pool.Spawned,"no replacement spawning");Check(KingdomEnhancedPlugin.Instance.LogSource.Lines.Any(l=>l.Contains("retired 2")),"actual retirement summary");});
  Test("SetActive deactivation followed by callback exception counts actual completed retirement",()=>{var f=Farm();var cats=Cats(f,6);foreach(var cat in cats)cat.gameObject.ThrowAfterDeactivate=true;Pool.Deferred=true;Stock(World());Eq(4,Alive(f),"exactly four remain after deferred Destroy and SetActive error");Eq(2,Pool.Retired.Count,"two completed retirements only");Eq(0,Pool.Spawned,"no extra supplementation");});
  Test("Still-active partial failure stops only its farmhouse and cannot over-delete after frame end",()=>{var uncertainFarm=Farm();Cats(uncertainFarm,6);var healthyFarm=Farm();Cats(healthyFarm,6);Pool.RetireOverride=go=>{if(go.GetComponent<Cat>().farmHouse==uncertainFarm){UnityEngine.Object.Destroy(go);throw new InvalidOperationException("Deferred native deletion queued before failure");}go.SetActive(false);};Stock(World());Eq(6,Alive(uncertainFarm),"pending deletion was not falsely counted");Eq(4,Alive(healthyFarm),"unrelated farmhouse still completes");Eq(1,Pool.Retired.Count(go=>go.GetComponent<Cat>().farmHouse==uncertainFarm),"no second uncertain candidate");Eq(2,Pool.Retired.Count(go=>go.GetComponent<Cat>().farmHouse==healthyFarm),"healthy farm retires exactly surplus");foreach(var go in Pool.Retired.Where(go=>go.PendingDestroy))go.SetActive(false);Eq(5,Alive(uncertainFarm),"later deferred completion cannot drop below four");Eq(0,Pool.Spawned,"no extra cats generated from uncertainty");});
  Test("Unobservable post-exception state is explicitly uncertain",()=>{var f=Farm();var cat=Cat(f);Pool.RetireOverride=go=>{go.ThrowOnActiveRead=true;throw new InvalidOperationException("Native state became unreadable");};bool result=Retire(cat,f,out bool uncertain);Check(!result&&uncertain,"cannot claim success when state cannot be observed");Eq(1,Pool.Retired.Count,"one attempted native operation");});
  Console.WriteLine($"RESULT {passed} passed, {failed} failed");Environment.ExitCode=failed==0?0:1;
 }
}
