using KingdomEnhancedMod;
using D=KingdomEnhancedMod.PatchRoles_CrossbowDefense;
static class Program {
 static int pass,fail,assertions;
 static void Check(bool v,string label){assertions++;if(!v)throw new Exception(label);}
 static void Eq(float a,float b,string label)=>Check(Math.Abs(a-b)<.001f,$"{label}: expected {a}, got {b}");
 static Archer New(){var a=new Archer();a.transform.position=new(99,0,0);a._mover._goalPosition=99;return a;}
 static void Test(string name,Action act){ModConfig.Enabled.Value=true;NetworkBigBoss.HasWorldAuth=true;Managers.Inst=new();try{act();Check(KingdomEnhancedPlugin.Logger.Errors.Count==0,"production error log");pass++;Console.WriteLine("PASS "+name);}catch(Exception e){fail++;Console.WriteLine("FAIL "+name+": "+e.Message);}}
 static void Main(){
 Test("both sides stable middle/rear band with wall reach",()=>{foreach(var side in new[]{Side.Left,Side.Right})for(int i=0;i<100;i++){var a=New();a._guardSide=side;float wall=Managers.Inst.kingdom.GetBorderSideIntact(side),s=(float)side;Check(D.TryGetNightGoal(a,wall-s,out var x),"redirect native wall goal");float depth=(wall-x)*s;Check(depth>=4&&depth<=7,"4..7 band");Check(12-depth>=5,"wall front reach margin");for(int j=0;j<3;j++){D.TryGetNightGoal(a,wall-s,out var again);Eq(x,again,"stable repeated target");}Check(!D.TryGetNightGoal(a,x,out _),"no redirect same target");}});
 Test("night and movement ownership exclusions",()=>{Action<Archer>[] changes={a=>a.Marked=false,a=>a._knight=new(),a=>a.inGuardSlot=true,a=>a._guardSlot=new(),a=>a.transform.position=new(99,3,0),a=>a._currentFormation=new(),a=>a.Controlled=true,a=>a._embarkee.IsEmbarked=true,a=>a._embarkee.EmbarkableTarget=new(),a=>a.WallDuty=false,a=>a.behaviour.latestGoto=64,a=>a.behaviour.latestGoto=16,a=>a._guardSide=Side.Neutral,a=>a.gameObject.activeInHierarchy=false};foreach(var change in changes){var a=New();change(a);Check(!D.TryGetNightGoal(a,99,out _),"excluded movement untouched");}foreach(float t in new[]{6f,12f,17f}){Managers.Inst.director.currentTime=t;Check(!D.TryGetNightGoal(New(),99,out _),"day excluded");}Managers.Inst.director.currentTime=20;NetworkBigBoss.HasWorldAuth=false;Check(!D.TryGetNightGoal(New(),99,out _),"client movement excluded");NetworkBigBoss.HasWorldAuth=true;ModConfig.Enabled.Value=false;Check(!D.TryGetNightGoal(New(),99,out _),"config off");});
 Test("narrow territory and unrelated destinations",()=>{var a=New();Check(!D.TryGetNightGoal(a,120,out _),"far outside untouched");Check(!D.TryGetNightGoal(a,0,out _),"unrelated deep goal untouched");Managers.Inst.kingdom.Right=3;Managers.Inst.kingdom.Left=-3;Check(D.TryGetNightGoal(a,2,out var x),"narrow valid target");Check(x>0&&x<3,"never cross campfire");Managers.Inst.kingdom.Right=.4f;Managers.Inst.kingdom.Left=-.4f;Check(!D.TryGetNightGoal(a,.3f,out _),"too narrow fail closed");});
 Test("pullback no teleport or repeated in-flight orders; displaced stopped unit resumes",()=>{var a=New();Check(D.TryPullBack(a),"initial pullback");Eq(99,a.transform.position.x,"no teleport");Check(!D.TryPullBack(a),"inflight not reissued");Eq(1,a._mover.Goals,"one order");a._mover._movingToGoal.value=false;Check(D.TryPullBack(a),"stopped displaced unit resumes");Eq(2,a._mover.Goals,"second order only after stopped");a.transform.position=new(95,0,0);Check(!D.TryPullBack(a),"already in band no movement");});
 Test("tower18 ground12 idempotence pending-slot and client",()=>{var a=New();a._enemyScanner.range=12;D.ReconcileTowerRange(a);Eq(18,a.towerShootRange,"tower capacity");Eq(12,a._enemyScanner.range,"ground scan unchanged");a._guardSlot=new();for(int i=0;i<25;i++)D.ReconcileTowerRange(a);Eq(18,a.towerShootRange,"no multiplier stack");Eq(18,a._enemyScanner.range,"pending tower scan");a._guardSlot=null;a.inGuardSlot=true;NetworkBigBoss.HasWorldAuth=false;D.ReconcileTowerRange(a);Eq(18,a._enemyScanner.rangeBehind,"client tower scan");a.inGuardSlot=false;a._enemyScanner.range=a._enemyScanner.rangeBehind=12;D.ReconcileTowerRange(a);Eq(12,a._enemyScanner.range,"native exit ground preserved");D.Remove(a);Eq(12,a.towerShootRange,"pool baseline restored");});
 Test("tower config/marker removal and fresh reuse baseline",()=>{var a=New();a.inGuardSlot=true;D.ReconcileTowerRange(a);ModConfig.Enabled.Value=false;D.ReconcileTowerRange(a);Eq(12,a.towerShootRange,"config restore");Eq(12,a._enemyScanner.range,"config scanner restore");ModConfig.Enabled.Value=true;D.ReconcileTowerRange(a);a.Marked=false;D.ReconcileTowerRange(a);Eq(12,a.towerShootRange,"marker loss restore");a.Marked=true;D.ReconcileTowerRange(a);D.Remove(a);a.towerShootRange=16;D.ReconcileTowerRange(a);Eq(24,a.towerShootRange,"fresh native baseline 16");D.Remove(a);Eq(16,a.towerShootRange,"fresh baseline restore");});
 Test("removal preserves external field/scanner writes independently",()=>{var a=New();a.inGuardSlot=true;D.ReconcileTowerRange(a);a.towerShootRange=21;a._enemyScanner.rangeBehind=25;D.Remove(a);Eq(21,a.towerShootRange,"external tower change");Eq(12,a._enemyScanner.range,"own front restored");Eq(25,a._enemyScanner.rangeBehind,"external rear preserved");D.Remove(a);Eq(21,a.towerShootRange,"remove idempotent");});
 Test("native disable clears tower flags before owned scan cleanup",()=>{var a=New();a.inGuardSlot=true;D.ReconcileTowerRange(a);a.inGuardSlot=false;a._guardSlot=null;a.gameObject.activeInHierarchy=false;D.Remove(a);Eq(12,a.towerShootRange,"pool tower baseline");Eq(12,a._enemyScanner.range,"pool front scan");Eq(12,a._enemyScanner.rangeBehind,"pool rear scan");a.gameObject.activeInHierarchy=true;D.ReconcileTowerRange(a);Eq(12,a._enemyScanner.range,"next ground life scan");});
 Test("narrow-territory arrived unit does not repeat orders",()=>{Managers.Inst.kingdom.Right=3;Managers.Inst.kingdom.Left=-3;var a=New();a._mover._goalPosition=2;D.TryGetNightGoal(a,2,out var target);a.transform.position=new(target,0,0);a._mover._goalPosition=target;a._mover._movingToGoal.value=false;Check(!D.TryPullBack(a),"arrived at clipped depth no order");Eq(0,a._mover.Goals,"no writes");});
 Console.WriteLine($"RESULT: {pass} passed, {fail} failed; {assertions} assertions");Environment.ExitCode=fail>0?1:0;
 }
}
