<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <DefaultItemExcludes>$(DefaultItemExcludes);**/obj/**;**/bin/**</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../il2cpp/HeavyShieldQuota.cs" Link="HeavyShieldQuota.cs" />
  </ItemGroup>
</Project>
