using System.Security.Cryptography;
using Mono.Cecil;
using Mono.Cecil.Cil;
if (args.Length != 3) throw new ArgumentException("input.dll helper.dll output.dll");
if (Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[0]))) != "EB2F9439633DDAA6A5B7BDD05C0ACD8224B383D6BE94F5E8D5088AE79E8164C2") throw new InvalidDataException("Unverified trampoline-patched input.");
using var original = AssemblyDefinition.ReadAssembly(args[0]);
using var asm = AssemblyDefinition.ReadAssembly(args[0]);
using var shim = AssemblyDefinition.ReadAssembly(args[1]);
var type = asm.MainModule.Types.Single(t => t.Name == "IL2CPPChainloader");
var method = type.Methods.Single(m => m.Name == "Initialize");
var match = method.Body.Instructions.Where(i => i.OpCode == OpCodes.Ldstr && (string)i.Operand == "il2cpp_runtime_invoke").ToArray();
if (match.Length != 1) throw new InvalidDataException("Unexpected export lookup count.");
var export = match[0].Next;
if (export.OpCode != OpCodes.Call || export.Operand is not MethodReference get || get.Name != "GetExport" || get.DeclaringType.FullName != "System.Runtime.InteropServices.NativeLibrary") throw new InvalidDataException("Unexpected export lookup shape.");
var resolver = shim.MainModule.Types.Single(t => t.Name == "RuntimeInvokeEntry").Methods.Single(m => m.Name == "ResolveRuntimeInvoke");
var added = Instruction.Create(OpCodes.Call, asm.MainModule.ImportReference(resolver));
method.Body.GetILProcessor().InsertAfter(export, added);
Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(args[2]))!);
asm.Write(args[2]);
using var result = AssemblyDefinition.ReadAssembly(args[2]);
static IEnumerable<MethodDefinition> Methods(TypeDefinition t) => t.Methods.Concat(t.NestedTypes.SelectMany(Methods));
static string Shape(MethodDefinition m, bool removeHelper) {
 if (!m.HasBody) return "NO_BODY";
 var ins = m.Body.Instructions.Where(i => !(removeHelper && i.Operand is MethodReference r && r.DeclaringType.FullName == "OhMyMods.Arm64Entry.RuntimeInvokeEntry" && r.Name == "ResolveRuntimeInvoke")).ToList();
 string Operand(object o) => o switch { null => "", Instruction i => "@" + ins.IndexOf(i), Instruction[] a => string.Join(",", a.Select(i => ins.IndexOf(i))), _ => o.ToString()! };
 return $"{m.Body.InitLocals}|{m.Body.MaxStackSize}|" + string.Join(";",m.Body.Variables.Select(v=>v.VariableType.FullName)) + "|" + string.Join(";",ins.Select(i=>i.OpCode+" "+Operand(i.Operand))) + "|" + string.Join(";",m.Body.ExceptionHandlers.Select(e=>$"{e.HandlerType}:{Operand(e.TryStart)}:{Operand(e.TryEnd)}:{Operand(e.HandlerStart)}:{Operand(e.HandlerEnd)}:{Operand(e.FilterStart)}:{e.CatchType}"));
}
var before = original.MainModule.Types.SelectMany(Methods).ToArray();
var after = result.MainModule.Types.SelectMany(Methods).ToArray();
if (before.Length != after.Length) throw new Exception("Method count changed.");
for(int i=0;i<before.Length;i++) if(before[i].FullName != after[i].FullName || Shape(before[i],false) != Shape(after[i],true)) throw new Exception("Unexpected IL change: " + before[i].FullName);
var helperCalls = after.Where(m=>m.HasBody).SelectMany(m=>m.Body.Instructions).Count(i=>i.Operand is MethodReference r && r.DeclaringType.FullName == "OhMyMods.Arm64Entry.RuntimeInvokeEntry");
if(helperCalls!=1) throw new Exception("Helper call count differs from one.");
var typed = after.Single(m=>m.DeclaringType.Name=="BaseNativeDetour`1" && m.Name=="GenerateTrampoline" && m.HasGenericParameters);
if(!typed.Body.Instructions.Any(i=>i.Operand is MethodReference r && r.Name=="Prepare") || !typed.Body.Instructions.Any(i=>i.Operand is MethodReference r && r.Name=="GetDelegateForFunctionPointer") || typed.Body.Instructions.Any(i=>i.Operand is MethodReference r && r.Name=="GenerateTrampoline")) throw new Exception("Typed trampoline repair missing.");
Console.WriteLine($"PASS: {before.Length} methods preserve original IL (excluding exactly one resolver call); typed Prepare+Marshal preserved.");
var patched = after.Single(m=>m.FullName==method.FullName);
foreach(var i in patched.Body.Instructions) Console.WriteLine(i);
Console.WriteLine("OUTPUT SHA256="+Convert.ToHexString(SHA256.HashData(File.ReadAllBytes(args[2]))));
