using System.Reflection;
using KingdomEnhancedMod;
using UnityEngine;
int passed=0;
void Check(bool value,string label){if(!value)throw new Exception(label);passed++;}
var root=new Persistent();var island=new IslandSaveData();
HeavyShieldShopShell.ThrowCancel=true;
var outer=HeavyShieldIntegration.BeginSave(0,0,-1);var first=HeavyShieldPersistence.LastSave;
Check(outer!=null&&first!=null,"cancel fault cannot block save capture");
HeavyShieldShopShell.ThrowCancel=false;HeavyShieldPersistence.ThrowBeginSave=true;
var inner=HeavyShieldIntegration.BeginSave(0,1,-1);
HeavyShieldIntegration.ObserveId(root,"masked");HeavyShieldIntegration.ObserveMarker(island);
Check(first.Ids==0&&first.Markers==0,"failed inner capture masks outer rows and marker");
HeavyShieldIntegration.EndSave(inner,false);HeavyShieldIntegration.EndSave(inner,true);
HeavyShieldPersistence.ThrowBeginSave=false;HeavyShieldIntegration.ObserveId(root,"owned");HeavyShieldIntegration.ObserveMarker(island);
Check(first.Ids==1&&first.Markers==1,"inner exit restores exact outer capture");
HeavyShieldPersistence.ThrowEndSave=true;HeavyShieldIntegration.EndSave(outer,true);
Check(HeavyShieldPersistence.EndSaveCalls==1&&HeavyShieldPersistence.LastSaveNormal,"normal flag reaches exact capture once");
HeavyShieldIntegration.EndSave(outer,true);HeavyShieldIntegration.ObserveId(root,"after-close");
Check(HeavyShieldPersistence.EndSaveCalls==1&&first.Ids==1,"throwing end closes once and never leaks capture");
HeavyShieldPersistence.ThrowEndSave=false;
var fresh=HeavyShieldIntegration.BeginSave(0,0,-1);HeavyShieldPersistence.ThrowId=true;
HeavyShieldIntegration.ObserveId(root,"throws");HeavyShieldPersistence.ThrowId=false;
HeavyShieldIntegration.EndSave(fresh,false);Check(!HeavyShieldPersistence.LastSaveNormal,"exceptional native return never becomes normal capture");
var load=HeavyShieldIntegration.BeginLoad(island);var parent=HeavyShieldPersistence.LastLoad;
HeavyShieldPersistence.ThrowBeginLoad=true;var failed=HeavyShieldIntegration.BeginLoad(island);
var row=new IslandSaveData.ObjectData();HeavyShieldIntegration.ObserveLoadRow(row,root);
Check(parent.Rows==0,"failed inner load never borrows outer row authority");
var local=HeavyShieldIntegration.BeginLoadRow(row);Check(local.Parent==null,"local row receives the inactive top capture");
HeavyShieldIntegration.EndLoadRow(local);Check(HeavyShieldPersistence.EndRowCalls==1,"local row always closes");
HeavyShieldIntegration.EndLoad(failed,false);HeavyShieldPersistence.ThrowBeginLoad=false;
HeavyShieldIntegration.ObserveLoadRow(row,root);Check(parent.Rows==1,"outer load restored after inactive inner");
HeavyShieldIntegration.EndLoad(load,true);HeavyShieldIntegration.EndLoad(load,false);
Check(HeavyShieldPersistence.EndLoadCalls==1&&HeavyShieldPersistence.LastLoadSuccess,"load closes once with actual success");
var prepare=HeavyShieldIntegration.BeginPrepare(new PrefsSaveData());
Check(prepare!=null&&HeavyShieldPersistence.PrepareCalls==1,"prepare prefix freezes exact per-call capture");
HeavyShieldIntegration.EndPrepare(prepare,true);
Check(HeavyShieldPersistence.EndPrepareCalls==1&&HeavyShieldPersistence.LastPrepareNormal,"normal native prepare return reaches capture receiver");
HeavyShieldIntegration.EndPrepare(prepare,false);
Check(!HeavyShieldPersistence.LastPrepareNormal,"native prepare exception cannot become normal return");
HeavyShieldPersistence.ThrowBeginPrepare=true;
Check(HeavyShieldIntegration.BeginPrepare(new PrefsSaveData())==null,"prepare begin failure is isolated from native save");
HeavyShieldPersistence.ThrowBeginPrepare=false;HeavyShieldPersistence.ThrowEndPrepare=true;
HeavyShieldIntegration.EndPrepare(prepare,false);HeavyShieldPersistence.ThrowEndPrepare=false;
Check(HeavyShieldPersistence.EndPrepareCalls==3,"prepare receiver exception is isolated");
HeavyShieldPersistence.ThrowBinding=true;HeavyShieldRuntime.ThrowTick=true;HeavyShieldIntegration.Tick();
Check(HeavyShieldRuntime.TickCalls==1&&HeavyShieldShopShell.TickCalls==1,"each module tick isolated from predecessor failures");
HeavyShieldPersistence.ThrowBinding=false;HeavyShieldRuntime.ThrowTick=false;ModConfig.HeavyShieldEnabled.Value=false;HeavyShieldIntegration.Tick();
Check(!HeavyShieldShopShell.LastEnabled,"disabled setting reaches shop cleanup");
var archer=new Archer();HeavyShieldIntegration.ObserveArcherEnable(archer);Check(HeavyShieldIdentity.Fresh==0,"ordinary enable never proves native fresh life");
HeavyShieldIntegration.BeginPoolSpawn();HeavyShieldRuntime.CarrierMutationInProgress=true;HeavyShieldIntegration.ObserveArcherEnable(archer);
Check(HeavyShieldIdentity.Fresh==0,"borrowed enabled write masks surrounding native pool scope");
HeavyShieldRuntime.CarrierMutationInProgress=false;HeavyShieldIntegration.ObserveArcherEnable(archer);
Check(HeavyShieldIdentity.Fresh==1&&HeavyShieldIntegration.InPoolSpawn,"real pool activation reaches life callback");
HeavyShieldIntegration.EndPoolSpawn();HeavyShieldIntegration.EndPoolSpawn();Check(!HeavyShieldIntegration.InPoolSpawn,"pool finalizer closure bounded");
HeavyShieldIntegration.BeforePoolDespawn(archer.gameObject,1);Check(HeavyShieldRuntime.DeathCalls==0,"delayed request does not confirm death");
HeavyShieldIntegration.BeforePoolDespawn(archer.gameObject,0);Check(HeavyShieldRuntime.DeathCalls==1,"immediate native boundary checks death before life end");
HeavyShieldIntegration.AfterPoolDespawn(archer.gameObject,0);Check(HeavyShieldIdentity.Despawn==0,"cached active root is not recycled");
archer.gameObject.activeInHierarchy=false;HeavyShieldIntegration.AfterPoolDespawn(archer.gameObject,0);Check(HeavyShieldIdentity.Despawn==1,"confirmed inactive native return reaches life end");
HeavyShieldRuntime.HeldDemoteSource=archer.gameObject;
HeavyShieldIntegration.AfterPoolDespawn(archer.gameObject,0);Check(HeavyShieldIdentity.Despawn==1,"exact source with whole-Demote proof stays Soldier until returned successor");
var unrelated=new GameObject{activeInHierarchy=false};HeavyShieldIntegration.AfterPoolDespawn(unrelated,0);
Check(HeavyShieldIdentity.Despawn==2,"same Demote window never masks unrelated pool event");
HeavyShieldRuntime.HeldDemoteSource=null;HeavyShieldIntegration.AfterPoolDespawn(archer.gameObject,0);
Check(HeavyShieldIdentity.Despawn==3,"unknown Demote source may become unresolved after proof scope closes");
bool Prefix(string nested,params object[] args)=>(bool)typeof(HeavyShieldCareerExclusion).GetNestedType(nested,BindingFlags.NonPublic).GetMethod("Before",BindingFlags.NonPublic|BindingFlags.Static).Invoke(null,args);
var embarkee=new Embarkee();var boat=new Embarkable();
Check(Prefix("TargetPatch",embarkee,boat)&&Prefix("EmbarkPatch",embarkee),"ordinary native boarding unchanged");
HeavyShieldIdentity.Roots.Add(embarkee.gameObject);
Check(!Prefix("TargetPatch",embarkee,boat)&&!Prefix("EmbarkPatch",embarkee),"owned shield blocks both independent boarding ingress");
Check(Prefix("TargetPatch",embarkee,null),"null target native cleanup remains available");
Console.WriteLine($"PASS {passed} assertions (real integration callbacks and boarding patch bodies; native boundaries modeled)");
