using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using System.Reflection;
using KingdomEnhancedMod;
using UnityEngine;
class Program {
 static int passed,failed; static Transform root;static Formation f;static readonly Type H=typeof(FleetGreekSquads);
 static void Assert(bool b,string s){if(!b)throw new Exception(s);}
 static void Test(string n,Action a){try{Reset();a();Console.WriteLine("PASS "+n);passed++;}catch(Exception e){Console.WriteLine("FAIL "+n+": "+e.GetBaseException().Message);failed++;}}
 static void Reset(){foreach(string n in new[]{"Boats","Knights","Retired","CancelBoats"}){var v=H.GetField(n,BindingFlags.NonPublic|BindingFlags.Static)?.GetValue(null);if(v is IDictionary d)d.Clear();if(v is IList l)l.Clear();}ModConfig.Enabled.Value=true;NetworkBigBoss.HasWorldAuth=true;Time.time=Time.realtimeSinceStartup=Time.unscaledTime=0;UnitScanCache.Roster.Clear();root=new GameObject().transform;Managers.Inst=new Managers{world=new World{gameLayer=root}};f=Make<Formation>();}
 static T Make<T>() where T:Component,new(){var go=new GameObject();go.transform.parent=root;return go.Add<T>();}
 static FleetBoat Boat(){var b=Make<FleetBoat>();b._embarkable=b.gameObject.Add<Embarkable>();return b;}
 static Knight K(int style=3,Side side=Side.Right){var k=Make<Knight>();k.style=style;k.side=side;k._embarkee=k.gameObject.Add<Embarkee>();UnitScanCache.Roster.Add(k);return k;}
 static List<FleetBoat> Select(params FleetBoat[] boats){var c=boats.ToList();FleetGreekSquads.Select(f,root,Side.Right,c);return c;}
 static void Registered(FleetBoat b,Formation form=null){form??=f;b._currentFormation=form;form.members.Add(b);b._fsm.Current=FleetBoat.State.InFormation;}
 static void Pair(out FleetBoat b,out Knight k){b=Boat();k=K();Assert(Select(b).Count==1,"pair");Registered(b);FleetGreekSquads.Complete(f);}
 static int Score(Embarkee e,Embarkable b,int score=123){var r=new EmbarkableRegistrar();r._tempUnitCache.Add(e);r._tempSlotCache.Add(new EmbarkeeSlot{Embarkable=b});object[] a={r,0,0,score};H.GetNestedType("ScorePatch",BindingFlags.NonPublic).GetMethod("Postfix",BindingFlags.NonPublic|BindingFlags.Static).Invoke(null,a);return (int)a[3];}
 static void Retire(Action<Knight,FleetBoat> mutate,bool shouldWrite=true){Pair(out var b,out var k);mutate(k,b);FleetGreekSquads.Prune();Assert(!FleetGreekSquads.Reserved(k),"reservation retired");Assert(f.Writes==0,"prune does not write");FleetGreekSquads.Maintain();Assert(f.Writes==(shouldWrite?1:0),"deferred writes="+f.Writes);}
 static void Main(){
  for(int bs=0;bs<=4;bs++)for(int ks=0;ks<=7;ks++){int bn=bs,kn=ks;Test($"min boats={bn} Greek={kn}",()=>{var b=Enumerable.Range(0,bn).Select(_=>Boat()).ToArray();for(int i=0;i<kn;i++)K();Assert(Select(b).Count==Math.Min(bn,kn),"count");});}
  Test("same side and Greek styles",()=>{var b=Boat();K(0);K(1);K(2);K(4);K(-1);K(3,Side.Left);Assert(Select(b).Count==0,"ineligible selected");var good=K();Assert(Select(b).Count==1&&FleetGreekSquads.Reserved(good),"Greek right");});
  Test("other boat and mainboat targets not stolen",()=>{var b=Boat();var other=Boat();K()._embarkee.EmbarkableTarget=other._embarkable;K()._embarkee.EmbarkableTarget=Make<Embarkable>();Assert(Select(b).Count==0,"target ownership");});
  Test("existing formation not stolen",()=>{K().formation=Make<Formation>();Assert(Select(Boat()).Count==0,"formation ownership");});
  Test("preassigned prioritized over lower id free",()=>{var b=Boat();var free=K();var assigned=K();assigned._embarkee.EmbarkableTarget=b._embarkable;Assert(Select(b).Count==1,"one pair");Assert(FleetGreekSquads.Reserved(assigned)&&!FleetGreekSquads.Reserved(free),"assigned priority");});
  Test("all own assignments protected before free fill",()=>{var first=Boat();var second=Boat();var assigned=K();assigned._embarkee.EmbarkableTarget=second._embarkable;var free=K();Assert(Select(first,second).Count==2,"two pairs");Assert(Score(assigned._embarkee,second._embarkable)==123&&Score(assigned._embarkee,first._embarkable)==100000,"correct assignment");});
  Test("two players global unique",()=>{var a=Boat();var b=Boat();var k=K();Select(a);var other=Make<Formation>();var c=new List<FleetBoat>{a,b};FleetGreekSquads.Select(other,root,Side.Right,c);Assert(c.Count==0,"same knight/boat reused");Assert(FleetGreekSquads.Reserved(k),"first reservation remains");});
  Test("legacy nonGreek embarked preserved and not candidate",()=>{var b=Boat();var k=K(1);k._embarkee.EmbarkableTarget=b._embarkable;k._embarkee.IsEmbarked=true;K();Assert(Select(b).Count==0,"legacy boat selected");Assert(Score(k._embarkee,b._embarkable,777)==777,"legacy score");});
  Test("new nonGreek rejected100000",()=>{Assert(Score(K(1)._embarkee,Boat()._embarkable)==100000,"score");});
  Test("other units and mainboat scores unchanged",()=>{Assert(Score(Make<Embarkee>(),Boat()._embarkable,-4000)==-4000,"worker");Assert(Score(K(1)._embarkee,Make<Embarkable>(),234)==234,"mainboat");});
  Test("native probe bypass restored",()=>{var b=Boat();Assert(!b.CanJoinFormation(Formation.FormationType.PlayerFormation,Side.Right),"unreserved gate");Assert(FleetGreekSquads.NativeCandidateCanJoin(b,Side.Right),"probe blocked");Assert(!b.CanJoinFormation(Formation.FormationType.PlayerFormation,Side.Right),"probe leaked");b.nativeCanJoin=false;Assert(!FleetGreekSquads.NativeCandidateCanJoin(b,Side.Right),"native false changed");});
  Test("pending survives frame before membership",()=>{var b=Boat();var k=K();Select(b);Time.time=1;FleetGreekSquads.Prune();Assert(FleetGreekSquads.Reserved(k),"pending lost");Registered(b);FleetGreekSquads.Complete(f);Assert(FleetGreekSquads.Reserved(k),"membership lost");});
  Test("complete failed boat clears",()=>{var b=Boat();var k=K();Select(b);FleetGreekSquads.Complete(f);Assert(!FleetGreekSquads.Reserved(k),"failed retained");FleetGreekSquads.Maintain();Assert(f.Writes==0,"failed mutated");});
  Test("external formation deferred cancellation",()=>Retire((k,b)=>k.formation=Make<Formation>()));
  Test("external mainboat target deferred cancellation",()=>Retire((k,b)=>k._embarkee.EmbarkableTarget=Make<Embarkable>()));
  Test("charge mission cancels",()=>Retire((k,b)=>k.isCharging=true));
  Test("player control cancels",()=>Retire((k,b)=>k._beingControlled=true));
  Test("puzzle mission cancels",()=>Retire((k,b)=>k.helPuzzlePillar=new object()));
  Test("death cancels",()=>Retire((k,b)=>k._damageable.isDead=true));
  Test("side change cancels",()=>Retire((k,b)=>k.side=Side.Left));
  Test("authority loss no writes",()=>Retire((k,b)=>NetworkBigBoss.HasWorldAuth=false,false));
  Test("world change no old world writes",()=>Retire((k,b)=>Managers.Inst.world.gameLayer=new GameObject().transform,false));
  Test("timeout60 deferred cancellation",()=>Retire((k,b)=>Time.time=61));
  Test("embarked survives deadline",()=>{Pair(out var b,out var k);k._embarkee.EmbarkableTarget=b._embarkable;k._embarkee.IsEmbarked=true;Time.time=61;FleetGreekSquads.Maintain();Assert(FleetGreekSquads.Reserved(k)&&f.Writes==0,"embarked expired");});
  Test("release does not unregister native memberships",()=>{Pair(out var b,out var k);FleetGreekSquads.Release(f);FleetGreekSquads.Maintain();Assert(!FleetGreekSquads.Reserved(k)&&f.Writes==0,"release write");});
  Test("cancel queue skips external boat formation",()=>{Pair(out var b,out var k);k.isCharging=true;FleetGreekSquads.Prune();var ext=Make<Formation>();b._currentFormation=ext;FleetGreekSquads.Maintain();Assert(f.Writes==0&&ext.Writes==0,"external touched");});
  Test("new plan supersedes old cancellation",()=>{Pair(out var b,out var k);k.isCharging=true;FleetGreekSquads.Prune();k.isCharging=false;Select(b);FleetGreekSquads.Maintain();Assert(f.Writes==0&&FleetGreekSquads.Reserved(k),"new plan cancelled");});
  Test("score failure queues without collection mutation",()=>{Pair(out var b,out var k);k.isCharging=true;Score(k._embarkee,b._embarkable);Assert(f.Writes==0,"score wrote");FleetGreekSquads.Maintain();Assert(f.Writes==1,"maintenance did not flush");});
  Test("native rejection unchanged",()=>Assert(Score(K()._embarkee,Boat()._embarkable,100000)==100000,"native rejection softened"));
  Test("disabled qualification stays native",()=>{ModConfig.Enabled.Value=false;Assert(Score(K(1)._embarkee,Boat()._embarkable,91)==91,"disabled score");});
  Test("client qualification stays native",()=>{NetworkBigBoss.HasWorldAuth=false;Assert(Score(K(1)._embarkee,Boat()._embarkable,91)==91,"client score");});
  Test("actual upstream boat snapshot same side and max4",()=>{var all=Enumerable.Range(1,4).Select(i=>{var b=Boat();b._boatNumber=i;return b;}).ToList();var wrong=Boat();wrong.Side=Side.Left;all.Add(wrong);var o=new List<FleetBoat>();Assert(CandidateSource.Build(Make<Player>(),f,new Kingdom{FleetBoats=all},root,Side.Right,o)&&o.Count==4,"candidate count");Assert(o.Select(b=>b._boatNumber).SequenceEqual(new[]{4,3,2,1}),"native registration order");for(int i=0;i<6;i++)K();FleetGreekSquads.Select(f,root,Side.Right,o);Assert(o.Count==4,"min after real upstream");});
  Test("actual upstream skips oldworld disabled occupied inaccessible",()=>{var valid=Boat();var old=Boat();old.transform.parent=new GameObject().transform;var disabled=Boat();disabled.enabled=false;var occupied=Boat();occupied._currentFormation=Make<Formation>();occupied._boatNumber=2;var far=Boat();far.IsAccessible=false;far._boatNumber=3;var o=new List<FleetBoat>();Assert(CandidateSource.Build(Make<Player>(),f,new Kingdom{FleetBoats=new(){valid,old,disabled,occupied,far}},root,Side.Right,o)&&o.Count==1&&o[0]==valid,"upstream exclusions");});
  Test("actual upstream duplicate boat numbers fails closed",()=>{var o=new List<FleetBoat>();Assert(!CandidateSource.Build(Make<Player>(),f,new Kingdom{FleetBoats=new(){Boat(),Boat()}},root,Side.Right,o),"duplicate accepted");});
  Test("unknown or multi squad prefab skipped",()=>{var a=Boat();a._numSquads=0;var b=Boat();b._numSquads=2;K();K();Assert(Select(a,b).Count==0,"capacity must be one");});
  Test("disabled knight cancels",()=>Retire((k,b)=>k.enabled=false));
  Test("harmless knight cancels",()=>Retire((k,b)=>k._harmless=true));
  Test("CanEmbark loss cancels",()=>Retire((k,b)=>k._embarkee.CanEmbark=false));
  Test("unassigned external FSM mission cancels",()=>Retire((k,b)=>k._fsm.Current=900));
  Test("native targeting embark FSM remains valid",()=>{Pair(out var b,out var k);k._embarkee.EmbarkableTarget=b._embarkable;k._fsm.Current=900;FleetGreekSquads.Maintain();Assert(FleetGreekSquads.Reserved(k)&&f.Writes==0,"embark route cancelled");});
  Test("pooled knight release clears previous lifetime",()=>{Pair(out var b,out var k);FleetGreekSquads.ReleaseKnight(k);Assert(!FleetGreekSquads.Reserved(k)&&f.Writes==0,"old identity retained or immediate write");FleetGreekSquads.Maintain();Assert(f.Writes==1,"old owned boat not cancelled");});
  Test("pooled release cannot cancel replacement pair",()=>{Pair(out var b,out var k);FleetGreekSquads.ReleaseKnight(k);Select(b);FleetGreekSquads.Maintain();Assert(FleetGreekSquads.Reserved(k)&&f.Writes==0,"replacement lost");});
  Test("world ledger clear drops queued writes",()=>{Pair(out var b,out var k);FleetGreekSquads.ReleaseKnight(k);FleetGreekSquads.Clear();FleetGreekSquads.Maintain();Assert(!FleetGreekSquads.Reserved(k)&&f.Writes==0,"queue survived Clear");Assert(!b.CanJoinFormation(Formation.FormationType.PlayerFormation,Side.Right),"boat ledger survived Clear");});
  Test("cancel queue world transition no old writes",()=>{Pair(out var b,out var k);FleetGreekSquads.ReleaseKnight(k);Managers.Inst.world.gameLayer=new GameObject().transform;FleetGreekSquads.Maintain();Assert(f.Writes==0,"queued old world mutation");});
  Test("cancel queue authority loss no writes",()=>{Pair(out var b,out var k);FleetGreekSquads.ReleaseKnight(k);NetworkBigBoss.HasWorldAuth=false;FleetGreekSquads.Maintain();Assert(f.Writes==0,"queued nonauthority mutation");});
  Test("actual finalizer native throw before postfix releases embarked pending",()=>{var b=Boat();var k=K();k._embarkee.EmbarkableTarget=b._embarkable;k._embarkee.IsEmbarked=true;Select(b);Time.time=1000;Assert(FleetGreekSquads.Reserved(k),"fixture must expose no embarked timeout");FinalizerSource.RestoreCalls=0;Exception thrown=null;try{throw new InvalidOperationException("native ActivateFormation before postfix");}catch(Exception e){thrown=e;Assert(ReferenceEquals(FinalizerSource.Run(e,f),e),"native exception changed");}Assert(thrown!=null&&!FleetGreekSquads.Reserved(k),"pending locked");Assert(FinalizerSource.RestoreCalls==1,"empty baseline not restored");FleetGreekSquads.Maintain();Assert(f.Writes==0,"unregistered boat touched");});
  Test("actual finalizer partial native membership null current is deferred removed",()=>{var b=Boat();var k=K();Select(b);f.members.Add(b);Assert(b._currentFormation==null,"partial registration fixture");FinalizerSource.RestoreCalls=0;FinalizerSource.Run(new Exception("native TryRecruit after RegisterUnit"),f);Assert(!FleetGreekSquads.Reserved(k)&&f.Writes==0,"finalizer must only retire and queue");Assert(FinalizerSource.RestoreCalls==0,"nonempty baseline restored prematurely");FleetGreekSquads.Maintain();Assert(f.Writes==1&&!f.members.Contains(b),"partial member not removed");});
  Test("actual finalizer partial membership other formation preserved",()=>{var b=Boat();var k=K();Select(b);f.members.Add(b);var external=Make<Formation>();b._currentFormation=external;FinalizerSource.Run(new Exception("native failure with later writer"),f);Assert(!FleetGreekSquads.Reserved(k),"failed pending retained");FleetGreekSquads.Maintain();Assert(f.Writes==0&&external.Writes==0&&f.members.Contains(b),"unrelated nonnull writer overridden");});
  Test("actual finalizer completed native member no longer pending",()=>{var b=Boat();var k=K();k._embarkee.EmbarkableTarget=b._embarkable;k._embarkee.IsEmbarked=true;Select(b);Registered(b);FinalizerSource.Run(new Exception("native failure after successful membership"),f);Assert(FleetGreekSquads.Reserved(k),"valid native member lost");b._currentFormation=null;FleetGreekSquads.Prune();Assert(!FleetGreekSquads.Reserved(k),"finalizer did not end pending");FleetGreekSquads.Maintain();Assert(f.Writes==1,"partial membership not cleaned");});
  Test("actual finalizer successful native return does not alter pending",()=>{var b=Boat();var k=K();Select(b);FinalizerSource.RestoreCalls=0;Assert(FinalizerSource.Run(null,f)==null&&FleetGreekSquads.Reserved(k),"success finalizer altered plan");Assert(FinalizerSource.RestoreCalls==0,"success restored baseline");});
  Test("native embark tween stationary own target survives maintenance",()=>{Pair(out var b,out var k);k._embarkee.EmbarkableTarget=b._embarkable;k._character.isStationary=true;k._embarkee.IsEmbarked=false;Time.time=0.5f;FleetGreekSquads.Maintain();Assert(FleetGreekSquads.Reserved(k)&&f.Writes==0,"OnEmbarkStart stationary tween cancelled");Time.time=1f;FleetGreekSquads.Maintain();Assert(FleetGreekSquads.Reserved(k)&&f.Writes==0,"second tween cadence cancelled");k._embarkee.IsEmbarked=true;Time.time=100;FleetGreekSquads.Maintain();Assert(FleetGreekSquads.Reserved(k)&&f.Writes==0,"completed embark cancelled");});
  Test("stationary without embark target cancels",()=>Retire((k,b)=>k._character.isStationary=true));
  Console.WriteLine($"RESULT passed={passed} failed={failed}");Environment.ExitCode=failed==0?0:1;
 }
}
