// <auto-generated> 由 native-review/native-geometry.json（operator 直 PPtr 证据）生成：
// 80 个原四 banker sprite 的 mesh 局部包络 + 真实 crop alpha 尺寸（alphaWidthPx/alphaHeightPx/
// alpha BBox 底边相对 pivot 行 BottomPx），供离线 fixture 断言使用。请勿手改。
internal static class NativeBankerFixture
{
    internal readonly struct Row
    {
        internal readonly string Name, Role, Clip;
        internal readonly int VertexCount;
        internal readonly float MinX, MinY, MaxX, MaxY;
        internal readonly int AlphaWidthPx, AlphaHeightPx;
        internal readonly float BottomPx;
        internal Row(string name, string role, string clip, int vertexCount,
            float minX, float minY, float maxX, float maxY, int alphaW, int alphaH, float bottomPx)
        {
            Name = name; Role = role; Clip = clip; VertexCount = vertexCount;
            MinX = minX; MinY = minY; MaxX = maxX; MaxY = maxY;
            AlphaWidthPx = alphaW; AlphaHeightPx = alphaH; BottomPx = bottomPx;
        }
    }

    internal static readonly Row[] Rows =
    {
        new Row("banker_idle_0", "banker", "banker_idle", 7, -0.3125f, 0.0f, 0.21875f, 0.8125f, 13, 24, 0.0f),
        new Row("banker_idle_1", "banker", "banker_idle", 6, -0.28125f, 0.0f, 0.21875f, 0.8125f, 12, 24, 0.0f),
        new Row("banker_idle_2", "banker", "banker_idle", 6, -0.25f, 0.0f, 0.1875f, 0.8125f, 10, 24, 0.0f),
        new Row("banker_idle_3", "banker", "banker_idle", 8, -0.25f, 0.0f, 0.1875f, 0.8125f, 10, 24, 0.0f),
        new Row("banker_idle_4", "banker", "banker_idle", 7, -0.25f, 0.0f, 0.1875f, 0.8125f, 10, 24, 0.0f),
        new Row("banker_idle_5", "banker", "banker_idle", 6, -0.25f, 0.0f, 0.1875f, 0.8125f, 10, 24, 0.0f),
        new Row("banker_idle_6", "banker", "banker_idle", 5, -0.25f, 0.0f, 0.21875f, 0.8125f, 11, 24, 0.0f),
        new Row("banker_idle_7", "banker", "banker_idle", 7, -0.28125f, 0.0f, 0.21875f, 0.8125f, 12, 24, 0.0f),
        new Row("banker_run_0", "banker", "banker_run", 10, -0.375f, 0.0f, 0.21875f, 0.8125f, 15, 24, 0.0f),
        new Row("banker_run_1", "banker", "banker_run", 7, -0.375f, 0.0f, 0.25f, 0.84375f, 16, 25, 0.0f),
        new Row("banker_run_2", "banker", "banker_run", 9, -0.375f, 0.0f, 0.25f, 0.875f, 16, 24, 2.0f),
        new Row("banker_run_3", "banker", "banker_run", 6, -0.375f, 0.0f, 0.25f, 0.8125f, 16, 24, 0.0f),
        new Row("banker_run_4", "banker", "banker_run", 7, -0.375f, 0.0f, 0.21875f, 0.84375f, 15, 25, 0.0f),
        new Row("banker_run_5", "banker", "banker_run", 9, -0.375f, 0.0f, 0.21875f, 0.875f, 15, 26, 0.0f),
        new Row("banker_walk_0", "banker", "banker_walk", 8, -0.3125f, 0.0f, 0.25f, 0.8125f, 14, 24, 0.0f),
        new Row("banker_walk_1", "banker", "banker_walk", 8, -0.3125f, 0.0f, 0.28125f, 0.8125f, 15, 24, 0.0f),
        new Row("banker_walk_2", "banker", "banker_walk", 8, -0.3125f, 0.0f, 0.28125f, 0.84375f, 15, 25, 0.0f),
        new Row("banker_walk_3", "banker", "banker_walk", 7, -0.3125f, 0.0f, 0.28125f, 0.8125f, 15, 24, 0.0f),
        new Row("banker_walk_4", "banker", "banker_walk", 9, -0.3125f, 0.0f, 0.25f, 0.8125f, 14, 24, 0.0f),
        new Row("banker_walk_5", "banker", "banker_walk", 8, -0.3125f, 0.0f, 0.25f, 0.84375f, 14, 25, 0.0f),
        new Row("banker_idle_0", "bamboo", "banker_idle_bamboo", 9, -0.34375f, 0.0f, 0.15625f, 0.75f, 12, 22, 0.0f),
        new Row("banker_idle_1", "bamboo", "banker_idle_bamboo", 6, -0.3125f, 0.0f, 0.15625f, 0.75f, 11, 22, 0.0f),
        new Row("banker_idle_2", "bamboo", "banker_idle_bamboo", 6, -0.3125f, 0.0f, 0.125f, 0.75f, 10, 22, 0.0f),
        new Row("banker_idle_3", "bamboo", "banker_idle_bamboo", 6, -0.3125f, 0.0f, 0.125f, 0.75f, 10, 22, 0.0f),
        new Row("banker_idle_4", "bamboo", "banker_idle_bamboo", 6, -0.3125f, 0.0f, 0.125f, 0.75f, 10, 22, 0.0f),
        new Row("banker_idle_5", "bamboo", "banker_idle_bamboo", 7, -0.3125f, 0.0f, 0.125f, 0.75f, 10, 22, 0.0f),
        new Row("banker_idle_6", "bamboo", "banker_idle_bamboo", 9, -0.3125f, 0.0f, 0.15625f, 0.75f, 11, 22, 0.0f),
        new Row("banker_idle_7", "bamboo", "banker_idle_bamboo", 9, -0.34375f, 0.0f, 0.15625f, 0.75f, 12, 22, 0.0f),
        new Row("banker_run_0", "bamboo", "banker_run_bamboo", 7, -0.34375f, 0.0f, 0.15625f, 0.75f, 12, 22, 0.0f),
        new Row("banker_run_1", "bamboo", "banker_run_bamboo", 9, -0.375f, 0.0f, 0.1875f, 0.8125f, 14, 24, 0.0f),
        new Row("banker_run_2", "bamboo", "banker_run_bamboo", 10, -0.375f, 0.0f, 0.1875f, 0.84375f, 14, 23, 2.0f),
        new Row("banker_run_3", "bamboo", "banker_run_bamboo", 10, -0.40625f, 0.0f, 0.1875f, 0.71875f, 15, 21, 0.0f),
        new Row("banker_run_4", "bamboo", "banker_run_bamboo", 9, -0.375f, 0.0f, 0.1875f, 0.75f, 14, 22, 0.0f),
        new Row("banker_run_5", "bamboo", "banker_run_bamboo", 7, -0.34375f, 0.0f, 0.1875f, 0.8125f, 13, 24, 0.0f),
        new Row("banker_walk_0", "bamboo", "banker_walk_bamboo", 8, -0.3125f, 0.0f, 0.125f, 0.75f, 10, 22, 0.0f),
        new Row("banker_walk_1", "bamboo", "banker_walk_bamboo", 8, -0.3125f, 0.0f, 0.1875f, 0.75f, 12, 22, 0.0f),
        new Row("banker_walk_2", "bamboo", "banker_walk_bamboo", 7, -0.34375f, 0.0f, 0.21875f, 0.75f, 14, 22, 0.0f),
        new Row("banker_walk_3", "bamboo", "banker_walk_bamboo", 10, -0.34375f, 0.0f, 0.21875f, 0.75f, 14, 22, 0.0f),
        new Row("banker_walk_4", "bamboo", "banker_walk_bamboo", 9, -0.3125f, 0.0f, 0.1875f, 0.75f, 12, 22, 0.0f),
        new Row("banker_walk_5", "bamboo", "banker_walk_bamboo", 10, -0.3125f, 0.0f, 0.15625f, 0.78125f, 11, 23, 0.0f),
        new Row("banker_idle_deadlands_0", "deadlands", "banker_idle_deadlands", 7, -0.21875f, 0.0f, 0.28125f, 0.65625f, 12, 19, 0.0f),
        new Row("banker_idle_deadlands_1", "deadlands", "banker_idle_deadlands", 8, -0.21875f, 0.0f, 0.25f, 0.65625f, 11, 19, 0.0f),
        new Row("banker_idle_deadlands_2", "deadlands", "banker_idle_deadlands", 6, -0.21875f, 0.0f, 0.21875f, 0.65625f, 10, 19, 0.0f),
        new Row("banker_idle_deadlands_3", "deadlands", "banker_idle_deadlands", 8, -0.21875f, 0.0f, 0.21875f, 0.65625f, 10, 19, 0.0f),
        new Row("banker_idle_deadlands_4", "deadlands", "banker_idle_deadlands", 8, -0.21875f, 0.0f, 0.21875f, 0.65625f, 10, 19, 0.0f),
        new Row("banker_idle_deadlands_5", "deadlands", "banker_idle_deadlands", 6, -0.21875f, 0.0f, 0.21875f, 0.65625f, 10, 19, 0.0f),
        new Row("banker_idle_deadlands_6", "deadlands", "banker_idle_deadlands", 8, -0.21875f, 0.0f, 0.25f, 0.65625f, 11, 19, 0.0f),
        new Row("banker_idle_deadlands_7", "deadlands", "banker_idle_deadlands", 7, -0.21875f, 0.0f, 0.28125f, 0.65625f, 12, 19, 0.0f),
        new Row("banker_run_deadlands_0", "deadlands", "banker_run_deadlands", 8, -0.28125f, 0.0f, 0.28125f, 0.6875f, 14, 18, 2.0f),
        new Row("banker_run_deadlands_1", "deadlands", "banker_run_deadlands", 8, -0.28125f, 0.0f, 0.3125f, 0.6875f, 15, 20, 0.0f),
        new Row("banker_run_deadlands_2", "deadlands", "banker_run_deadlands", 10, -0.25f, 0.0f, 0.3125f, 0.65625f, 14, 19, 0.0f),
        new Row("banker_run_deadlands_3", "deadlands", "banker_run_deadlands", 9, -0.28125f, 0.0f, 0.3125f, 0.65625f, 15, 18, 1.0f),
        new Row("banker_run_deadlands_4", "deadlands", "banker_run_deadlands", 9, -0.28125f, 0.0f, 0.3125f, 0.625f, 15, 18, 0.0f),
        new Row("banker_run_deadlands_5", "deadlands", "banker_run_deadlands", 8, -0.3125f, 0.0f, 0.28125f, 0.625f, 15, 18, 0.0f),
        new Row("banker_walk_deadlands_0", "deadlands", "banker_walk_deadlands", 8, -0.21875f, 0.0f, 0.28125f, 0.65625f, 12, 19, 0.0f),
        new Row("banker_walk_deadlands_1", "deadlands", "banker_walk_deadlands", 7, -0.25f, 0.0f, 0.3125f, 0.625f, 14, 18, 0.0f),
        new Row("banker_walk_deadlands_2", "deadlands", "banker_walk_deadlands", 9, -0.28125f, 0.0f, 0.3125f, 0.65625f, 15, 19, 0.0f),
        new Row("banker_walk_deadlands_3", "deadlands", "banker_walk_deadlands", 10, -0.25f, 0.0f, 0.3125f, 0.65625f, 14, 19, 0.0f),
        new Row("banker_walk_deadlands_4", "deadlands", "banker_walk_deadlands", 8, -0.21875f, 0.0f, 0.3125f, 0.625f, 13, 18, 0.0f),
        new Row("banker_walk_deadlands_5", "deadlands", "banker_walk_deadlands", 7, -0.21875f, 0.0f, 0.28125f, 0.65625f, 12, 19, 0.0f),
        new Row("banker_idle_norselands_0", "norselands", "banker_idle_norselands", 8, -0.25f, 0.0f, 0.28125f, 0.65625f, 13, 19, 0.0f),
        new Row("banker_idle_norselands_1", "norselands", "banker_idle_norselands", 8, -0.25f, 0.0f, 0.25f, 0.65625f, 12, 19, 0.0f),
        new Row("banker_idle_norselands_2", "norselands", "banker_idle_norselands", 8, -0.21875f, 0.0f, 0.21875f, 0.65625f, 10, 19, 0.0f),
        new Row("banker_idle_norselands_3", "norselands", "banker_idle_norselands", 8, -0.21875f, 0.0f, 0.21875f, 0.65625f, 10, 19, 0.0f),
        new Row("banker_idle_norselands_4", "norselands", "banker_idle_norselands", 8, -0.21875f, 0.0f, 0.21875f, 0.65625f, 10, 19, 0.0f),
        new Row("banker_idle_norselands_5", "norselands", "banker_idle_norselands", 8, -0.21875f, 0.0f, 0.21875f, 0.65625f, 10, 19, 0.0f),
        new Row("banker_idle_norselands_6", "norselands", "banker_idle_norselands", 8, -0.25f, 0.0f, 0.25f, 0.65625f, 12, 19, 0.0f),
        new Row("banker_idle_norselands_7", "norselands", "banker_idle_norselands", 8, -0.25f, 0.0f, 0.28125f, 0.65625f, 13, 19, 0.0f),
        new Row("banker_run_norselands_0", "norselands", "banker_run_norselands", 7, -0.28125f, 0.0f, 0.28125f, 0.6875f, 14, 18, 2.0f),
        new Row("banker_run_norselands_1", "norselands", "banker_run_norselands", 8, -0.28125f, 0.0f, 0.3125f, 0.65625f, 15, 19, 0.0f),
        new Row("banker_run_norselands_2", "norselands", "banker_run_norselands", 8, -0.25f, 0.0f, 0.3125f, 0.65625f, 14, 19, 0.0f),
        new Row("banker_run_norselands_3", "norselands", "banker_run_norselands", 8, -0.28125f, 0.0f, 0.3125f, 0.6875f, 15, 19, 1.0f),
        new Row("banker_run_norselands_4", "norselands", "banker_run_norselands", 9, -0.28125f, 0.0f, 0.3125f, 0.65625f, 15, 19, 0.0f),
        new Row("banker_run_norselands_5", "norselands", "banker_run_norselands", 9, -0.3125f, 0.0f, 0.28125f, 0.65625f, 15, 19, 0.0f),
        new Row("banker_walk_norselands_0", "norselands", "banker_walk_norselands", 6, -0.25f, 0.0f, 0.28125f, 0.65625f, 13, 19, 0.0f),
        new Row("banker_walk_norselands_1", "norselands", "banker_walk_norselands", 9, -0.25f, 0.0f, 0.3125f, 0.625f, 14, 18, 0.0f),
        new Row("banker_walk_norselands_2", "norselands", "banker_walk_norselands", 6, -0.28125f, 0.0f, 0.3125f, 0.65625f, 15, 19, 0.0f),
        new Row("banker_walk_norselands_3", "norselands", "banker_walk_norselands", 9, -0.25f, 0.0f, 0.3125f, 0.65625f, 14, 19, 0.0f),
        new Row("banker_walk_norselands_4", "norselands", "banker_walk_norselands", 10, -0.25f, 0.0f, 0.3125f, 0.625f, 14, 18, 0.0f),
        new Row("banker_walk_norselands_5", "norselands", "banker_walk_norselands", 9, -0.25f, 0.0f, 0.28125f, 0.65625f, 13, 19, 0.0f),
    };
}
